# 01 · Evaluacion de LLMs con lm-evaluation-harness · base vs instruct

> Demo práctica del módulo de Evaluación. Cargas Qwen3-4B base, lo mides en 3 benchmarks. Luego cargas Qwen3-4B instruct, mides los mismos benchmarks. **Cierras con una tabla comparativa** que ensena el efecto del instruct tuning en numeros reales... y por que esos numeros dependen del protocolo de evaluacion.

## Que aprendemos

1. **lm-evaluation-harness** · la libreria de Eleuther AI que alimenta el Open LLM Leaderboard.
2. **3 benchmarks clasicos** · HellaSwag (sentido comun), ARC-Easy (razonamiento basico), MMLU-ML (conocimiento).
3. **Diferencia base vs instruct** · ¿cuanto sube por hacer instruct tuning?
4. **`acc` vs `acc_norm`** · la metrica canonica de HellaSwag (length-normalized).
5. **Cuantizacion 4-bit en evaluacion** · sirve para fitting en T4 sin afectar el ranking relativo.

## Por que importa

La pregunta natural al terminar el módulo de Fine-tuning es **¿cuanto mejora mi modelo?**. Este módulo te da el lenguaje para responderla con numeros publicos comparables.

Tambien aterriza la critica honesta · los benchmarks **clasicos** (MMLU, HumanEval, ARC-AGI-1) estan saturados en 2026. La frontera real es **MMLU-Pro, GPQA Diamond, SWE-bench Pro, HLE, ARC-AGI-2**. Lo veras en las slides 20 y 26.

## Conecta con

- **Slides de Evaluación** · benchmarks clasicos (9-17), critica (18-19), frontier vs local (20), este notebook (24), benchmarks vigentes 2026 (26).
- **Lab 09 de Fine-tuning** · alli mediste tus adapters de los labs 04 (Milei) y 05 (distillation) con una version minima (ARC con 20 preguntas, toxicidad, juez). Aqui ves la herramienta estandar que lo hace a escala.
- **Labs 04 y 05 de Fine-tuning** · al final tienes la receta para pasar tus adapters por este mismo harness.
- **Módulo de evaluación de LLM apps (clase 6)** · aqui evaluas el MODELO · alli evaluaras tu APP entera.

## Stack

`Qwen3-4B` base + instruct (selector `MODEL_SIZE`: 14B en A100) · `lm-evaluation-harness` (Eleuther AI) · `BitsAndBytesConfig` (NF4 4-bit) · `pandas` (comparativa).

## Hardware

T4 (Colab Free, 16GB VRAM) vale con 4-bit. Con `LIMIT = 500` (por defecto) el notebook entero tarda **~35 min** en T4 (ejecucion de referencia, oct-2026). Con `LIMIT = None` (HellaSwag completo, ~40k pasadas por modelo) son horas en T4: dejalo para A100/H100.

---

## Setup

`lm-evaluation-harness` es el framework de referencia. Lo instalamos **una sola vez** desde PyPI (`lm-eval[hf]`): trae el backend de HuggingFace y no toca las librerias preinstaladas de Colab mas de lo necesario. **Tambien** existe `lighteval` (HuggingFace) que cubre lo mismo con API mas moderna · la veremos en la celda final.

In [1]:
!pip install -q "lm-eval[hf]" bitsandbytes

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 4.3 MB/s eta 0:00:00

  Preparing metadata (setup.py) ... done

  Preparing metadata (setup.py) ... done

  Preparing metadata (setup.py) ... done

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/43.1 MB 183.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 43.1/43.1 MB 212.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 43.1/43.1 MB 212.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 25.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 6.3/9.1 MB 200.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 108.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/129.6 kB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 14.0 MB/s eta 0:00:00

  Building wheel for rouge-score (setup.py) ... done

  Building wheel for sqlitedict (setup.py) ... done

  Building wheel for word2number (setup.py) ... done

### Login HuggingFace

`Qwen3-4B-Base` y `Qwen3-4B` son **open weights (Apache 2.0)**: no hay que aceptar ninguna licencia gated. Solo necesitas tu [token de HF](https://huggingface.co/settings/tokens) para el login (descargas mas rapidas):

In [3]:
# Login a HuggingFace (token desde huggingface.co/settings/tokens)
from huggingface_hub import notebook_login
notebook_login()

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

WARNING:huggingface_hub._login:Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

---

## Configuracion de evaluacion (reutilizable)

Definimos todo lo que NO cambia entre los 2 modelos: BitsAndBytesConfig + lista de benchmarks + funcion para correr eval. Asi solo cambia `MODEL_ID` entre las 2 partes.

In [5]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# Quant config canonica · NF4 + double quant (paper QLoRA).
# Compute en bf16 si la GPU lo soporta de forma nativa (Ampere o posterior: A100/L4/H100).
# La T4 (Turing, capacidad 7.5) solo lo emula y va mucho mas lenta -> fp16.
# (Ojo: torch.cuda.is_bf16_supported() devuelve True en T4 porque cuenta la emulacion.)
COMPUTE_DTYPE = torch.bfloat16 if torch.cuda.get_device_capability()[0] >= 8 else torch.float16
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=COMPUTE_DTYPE,
)
print("Compute dtype:", COMPUTE_DTYPE)

# Modelo a evaluar: base vs instruct del MISMO tamano. Cambia MODEL_SIZE y listo.
MODEL_SIZE = "mini"   # "mini" (T4, 4-bit) · "big" (A100/H100)
MODELS = {
    "mini": ("Qwen/Qwen3-4B-Base",  "Qwen/Qwen3-4B"),    # ~4B en 4-bit cabe en T4 (Qwen3, 2025)
    "big":  ("Qwen/Qwen3-14B-Base", "Qwen/Qwen3-14B"),   # 14B -> A100/H100
}
MODEL_ID_BASE, MODEL_ID_INSTRUCT = MODELS[MODEL_SIZE]
print("Base:", MODEL_ID_BASE, "| Instruct:", MODEL_ID_INSTRUCT)

# Benchmarks que usaremos
TASKS_BASIC = ["hellaswag", "arc_easy"]
TASK_MMLU = "mmlu_flan_n_shot_loglikelihood_machine_learning"
TASK_MMLU_COT = "mmlu_flan_cot_zeroshot_machine_learning"

# Ejemplos por benchmark. HellaSwag completo son 10.042 preguntas x 4 finales = ~40k forward passes:
# en una T4 son HORAS. Con LIMIT = 500 (500 de HellaSwag y 500 de ARC-Easy) la comparativa es
# estable (error estandar ~2 puntos) y el notebook entero cabe en clase.
# MMLU machine_learning tiene 112 preguntas: el limite no le afecta. None = benchmark completo (A100/H100).
LIMIT = 500

Compute dtype: torch.float16
Base: Qwen/Qwen3-4B-Base | Instruct: Qwen/Qwen3-4B

In [7]:
import lm_eval
from lm_eval.tasks import TaskManager
from lm_eval.models.huggingface import HFLM
import pandas as pd
import gc

task_manager = TaskManager()


def load_model(model_id):
    """Carga modelo + tokenizer en 4-bit."""
    print(f"Loading {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        dtype=COMPUTE_DTYPE,
        device_map="auto",
    )
    # Qwen trae max_new_tokens=2048 en su generation_config, y eso PISA el limite de generacion
    # que fija lm-eval (max_gen_toks). Lo quitamos para que mande lm-eval.
    model.generation_config.max_new_tokens = None
    print(f"  VRAM: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    return model, tokenizer


def free_model():
    """Libera VRAM antes de cargar el siguiente modelo.

    OJO: hay que hacer `del model_base` FUERA de la funcion. Un `del model` dentro de la funcion
    solo borra la variable local: la global sigue apuntando al modelo y la VRAM no se libera.
    """
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    print(f"  VRAM tras liberar: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")


def eval_basic(model):
    """HellaSwag + ARC-Easy · 0-shot."""
    return lm_eval.simple_evaluate(
        model=HFLM(model, batch_size=8),
        tasks=TASKS_BASIC,
        task_manager=task_manager,
        num_fewshot=0,
        batch_size=8,
        limit=LIMIT,
    )


def eval_mmlu(model, num_fewshot):
    """MMLU machine_learning subset · n-shot loglikelihood."""
    return lm_eval.simple_evaluate(
        model=HFLM(model, batch_size=8),
        tasks=[TASK_MMLU],
        task_manager=task_manager,
        num_fewshot=num_fewshot,
        batch_size=8,
        limit=LIMIT,
    )


def eval_mmlu_cot(model):
    """MMLU machine_learning CoT 0-shot.

    Tarea generativa: el modelo escribe el razonamiento y luego "The answer is (X)".
    Limitamos a 384 tokens por respuesta (gen_kwargs). Sin limite, el modelo base no para de escribir
    y en una T4 la CoT sola tarda mas de media hora por modelo.
    Ojo: esta variante de lm-eval usa el split de validacion de MMLU-ML (11 preguntas): es una DEMO,
    mira el stderr antes de sacar conclusiones.
    """
    return lm_eval.simple_evaluate(
        model=HFLM(model, batch_size=4),
        tasks=[TASK_MMLU_COT],
        task_manager=task_manager,
        num_fewshot=0,
        batch_size=4,
        limit=LIMIT,
        gen_kwargs={"max_gen_toks": 384},
    )


def extract(results, task, metric="acc,none"):
    """Extrae una metrica concreta del dict de resultados."""
    return results["results"][task].get(metric, None)


print("Helpers definidos. Vamos.")

Helpers definidos. Vamos.

---

# Parte A · Modelo BASE (`MODEL_ID_BASE`)

Un modelo base **no** ha pasado por el post-entrenamiento (SFT + preferencias/RL). Predice el siguiente token y ya.

La hipotesis clasica (la que se cumplia con los base de 2020-2023):

- Le cuesta el formato "responde A/B/C/D".
- Le cuesta la CoT (no sabe generar razonamientos estructurados · solo continua texto).
- Va bien en tareas de pura continuacion (HellaSwag normalizado).

Ojo: los base de 2025-2026 (como `Qwen3-4B-Base`) se pre-entrenan con muchisimos datos de razonamiento e instrucciones. **Vamos a medir si la hipotesis sigue en pie.**

In [8]:
model_base, tokenizer_base = load_model(MODEL_ID_BASE)   # MODEL_ID_BASE viene del selector de arriba

Loading Qwen/Qwen3-4B-Base...

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.68k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/32.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

  VRAM: 2.49 GB

### A.1 · HellaSwag + ARC-Easy (0-shot)

Estos 2 son los benchmarks ligeros del antiguo Open LLM Leaderboard (v1). Con `LIMIT = 500`: ~3-4 min en T4 en 4-bit.

In [ ]:
results_base_basic = eval_basic(model_base)
pd.DataFrame(results_base_basic["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

README.md:   0%|          | 0.00/7.02k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 24.4MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.11MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.32MB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/39905 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10003 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10042 [00:00<?, ? examples/s]

Map:   0%|          | 0/39905 [00:00<?, ? examples/s]

Map:   0%|          | 0/10042 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/9.00k [00:00<?, ?B/s]

ARC-Easy/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  331kB

ARC-Easy/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

ARC-Easy/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  346kB

ARC-Easy/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

ARC-Easy/validation-00000-of-00001.parqu(…): reconstructing file:   0%|          |  0.00B / 86.1kB

ARC-Easy/validation-00000-of-00001.parqu(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2251 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2376 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/570 [00:00<?, ? examples/s]

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of hellaswag from None to 0

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of arc_easy from None to 0

  0%|          | 0/500 [00:00<?, ?it/s]

 22%|██▏       | 110/500 [00:00<00:00, 1091.04it/s]

 44%|████▍     | 220/500 [00:00<00:00, 1080.12it/s]

 66%|██████▋   | 332/500 [00:00<00:00, 1095.53it/s]

 90%|█████████ | 451/500 [00:00<00:00, 1130.14it/s]

100%|██████████| 500/500 [00:00<00:00, 1116.78it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  9%|▉         | 46/500 [00:00<00:00, 455.72it/s]

 18%|█▊        | 92/500 [00:00<00:00, 453.77it/s]

 28%|██▊       | 138/500 [00:00<00:00, 455.36it/s]

 37%|███▋      | 184/500 [00:00<00:00, 428.95it/s]

 46%|████▌     | 231/500 [00:00<00:00, 441.42it/s]

 55%|█████▌    | 277/500 [00:00<00:00, 446.72it/s]

 64%|██████▍   | 322/500 [00:00<00:00, 447.51it/s]

 74%|███████▎  | 368/500 [00:00<00:00, 450.25it/s]

 83%|████████▎ | 415/500 [00:00<00:00, 453.87it/s]

 92%|█████████▏| 461/500 [00:01<00:00, 454.59it/s]

100%|██████████| 500/500 [00:01<00:00, 450.06it/s]

Tokenizing inputs:   0%|          | 0/3998 [00:00<?, ?it/s]

Tokenizing inputs:   8%|▊         | 318/3998 [00:00<00:01, 3174.89it/s]

Tokenizing inputs:  17%|█▋        | 694/3998 [00:00<00:00, 3514.88it/s]

Tokenizing inputs:  26%|██▌       | 1046/3998 [00:00<00:00, 3251.01it/s]

Tokenizing inputs:  36%|███▌      | 1429/3998 [00:00<00:00, 3464.65it/s]

Tokenizing inputs:  45%|████▌     | 1813/3998 [00:00<00:00, 3595.55it/s]

Tokenizing inputs:  56%|█████▌    | 2237/3998 [00:00<00:00, 3809.81it/s]

Tokenizing inputs:  66%|██████▌   | 2636/3998 [00:00<00:00, 3866.70it/s]

Tokenizing inputs:  76%|███████▋  | 3056/3998 [00:00<00:00, 3970.92it/s]

Tokenizing inputs:  87%|████████▋ | 3495/3998 [00:00<00:00, 4095.77it/s]

Tokenizing inputs:  98%|█████████▊| 3933/3998 [00:01<00:00, 4179.56it/s]

Tokenizing inputs: 100%|██████████| 3998/3998 [00:01<00:00, 3844.60it/s]

Running loglikelihood requests:   0%|          | 0/3998 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/3998 [00:02<2:36:19,  2.35s/it]

Running loglikelihood requests:   0%|          | 9/3998 [00:02<15:59,  4.16it/s]

Running loglikelihood requests:   0%|          | 17/3998 [00:03<08:50,  7.50it/s]

Running loglikelihood requests:   1%|          | 26/3998 [00:03<06:01, 10.98it/s]

Running loglikelihood requests:   1%|          | 34/3998 [00:04<04:58, 13.30it/s]

Running loglikelihood requests:   1%|          | 42/3998 [00:04<04:14, 15.54it/s]

Running loglikelihood requests:   1%|▏         | 50/3998 [00:04<03:46, 17.42it/s]

Running loglikelihood requests:   1%|▏         | 58/3998 [00:05<03:27, 18.97it/s]

Running loglikelihood requests:   2%|▏         | 66/3998 [00:05<03:14, 20.18it/s]

Running loglikelihood requests:   2%|▏         | 74/3998 [00:05<03:06, 21.10it/s]

Running loglikelihood requests:   2%|▏         | 82/3998 [00:06<02:59, 21.84it/s]

Running loglikelihood requests:   2%|▏         | 90/3998 [00:06<02:54, 22.33it/s]

Running loglikelihood requests:   2%|▏         | 98/3998 [00:06<02:51, 22.75it/s]

Running loglikelihood requests:   3%|▎         | 106/3998 [00:07<02:48, 23.11it/s]

Running loglikelihood requests:   3%|▎         | 114/3998 [00:07<02:46, 23.34it/s]

Running loglikelihood requests:   3%|▎         | 122/3998 [00:07<02:44, 23.59it/s]

Running loglikelihood requests:   3%|▎         | 130/3998 [00:08<02:42, 23.73it/s]

Running loglikelihood requests:   3%|▎         | 138/3998 [00:08<02:41, 23.87it/s]

Running loglikelihood requests:   4%|▎         | 146/3998 [00:08<02:40, 23.98it/s]

Running loglikelihood requests:   4%|▍         | 154/3998 [00:09<02:40, 24.02it/s]

Running loglikelihood requests:   4%|▍         | 162/3998 [00:09<02:38, 24.20it/s]

Running loglikelihood requests:   4%|▍         | 170/3998 [00:09<02:37, 24.28it/s]

Running loglikelihood requests:   4%|▍         | 178/3998 [00:10<02:30, 25.34it/s]

Running loglikelihood requests:   5%|▍         | 186/3998 [00:10<02:25, 26.17it/s]

Running loglikelihood requests:   5%|▍         | 194/3998 [00:10<02:22, 26.73it/s]

Running loglikelihood requests:   5%|▌         | 202/3998 [00:10<02:19, 27.14it/s]

Running loglikelihood requests:   5%|▌         | 210/3998 [00:11<02:17, 27.45it/s]

Running loglikelihood requests:   5%|▌         | 218/3998 [00:11<02:16, 27.69it/s]

Running loglikelihood requests:   6%|▌         | 226/3998 [00:11<02:15, 27.88it/s]

Running loglikelihood requests:   6%|▌         | 234/3998 [00:11<02:14, 27.95it/s]

Running loglikelihood requests:   6%|▌         | 242/3998 [00:12<02:13, 28.06it/s]

Running loglikelihood requests:   6%|▋         | 250/3998 [00:12<02:12, 28.23it/s]

Running loglikelihood requests:   6%|▋         | 258/3998 [00:12<02:11, 28.42it/s]

Running loglikelihood requests:   7%|▋         | 266/3998 [00:13<02:10, 28.63it/s]

Running loglikelihood requests:   7%|▋         | 274/3998 [00:13<02:10, 28.63it/s]

Running loglikelihood requests:   7%|▋         | 283/3998 [00:13<02:05, 29.69it/s]

Running loglikelihood requests:   7%|▋         | 291/3998 [00:13<02:05, 29.45it/s]

Running loglikelihood requests:   7%|▋         | 299/3998 [00:14<02:05, 29.38it/s]

Running loglikelihood requests:   8%|▊         | 307/3998 [00:14<02:06, 29.22it/s]

Running loglikelihood requests:   8%|▊         | 315/3998 [00:14<02:06, 29.16it/s]

Running loglikelihood requests:   8%|▊         | 323/3998 [00:15<02:05, 29.20it/s]

Running loglikelihood requests:   8%|▊         | 331/3998 [00:15<02:06, 29.04it/s]

Running loglikelihood requests:   8%|▊         | 339/3998 [00:15<02:06, 29.03it/s]

Running loglikelihood requests:   9%|▊         | 347/3998 [00:15<02:05, 29.06it/s]

Running loglikelihood requests:   9%|▉         | 355/3998 [00:16<02:05, 29.03it/s]

Running loglikelihood requests:   9%|▉         | 363/3998 [00:16<02:04, 29.14it/s]

Running loglikelihood requests:   9%|▉         | 371/3998 [00:16<02:04, 29.22it/s]

Running loglikelihood requests:   9%|▉         | 379/3998 [00:16<02:03, 29.29it/s]

Running loglikelihood requests:  10%|▉         | 387/3998 [00:17<02:03, 29.21it/s]

Running loglikelihood requests:  10%|▉         | 395/3998 [00:17<02:02, 29.40it/s]

Running loglikelihood requests:  10%|█         | 403/3998 [00:17<02:01, 29.47it/s]

Running loglikelihood requests:  10%|█         | 414/3998 [00:18<01:48, 32.97it/s]

Running loglikelihood requests:  11%|█         | 422/3998 [00:18<01:51, 32.01it/s]

Running loglikelihood requests:  11%|█         | 430/3998 [00:18<01:53, 31.49it/s]

Running loglikelihood requests:  11%|█         | 438/3998 [00:18<01:54, 31.05it/s]

Running loglikelihood requests:  11%|█         | 446/3998 [00:19<01:55, 30.64it/s]

Running loglikelihood requests:  11%|█▏        | 456/3998 [00:19<01:48, 32.68it/s]

Running loglikelihood requests:  12%|█▏        | 464/3998 [00:19<01:50, 32.00it/s]

Running loglikelihood requests:  12%|█▏        | 472/3998 [00:19<01:52, 31.45it/s]

Running loglikelihood requests:  12%|█▏        | 480/3998 [00:20<01:53, 31.09it/s]

Running loglikelihood requests:  12%|█▏        | 488/3998 [00:20<01:53, 30.90it/s]

Running loglikelihood requests:  12%|█▏        | 496/3998 [00:20<01:54, 30.70it/s]

Running loglikelihood requests:  13%|█▎        | 506/3998 [00:20<01:46, 32.91it/s]

Running loglikelihood requests:  13%|█▎        | 514/3998 [00:21<01:48, 32.11it/s]

Running loglikelihood requests:  13%|█▎        | 522/3998 [00:21<01:50, 31.45it/s]

Running loglikelihood requests:  13%|█▎        | 530/3998 [00:21<01:51, 31.07it/s]

Running loglikelihood requests:  13%|█▎        | 538/3998 [00:22<01:52, 30.73it/s]

Running loglikelihood requests:  14%|█▎        | 549/3998 [00:22<01:41, 34.01it/s]

Running loglikelihood requests:  14%|█▍        | 557/3998 [00:22<01:44, 32.94it/s]

Running loglikelihood requests:  14%|█▍        | 565/3998 [00:22<01:46, 32.31it/s]

Running loglikelihood requests:  14%|█▍        | 573/3998 [00:23<01:47, 31.78it/s]

Running loglikelihood requests:  15%|█▍        | 581/3998 [00:23<01:49, 31.34it/s]

Running loglikelihood requests:  15%|█▍        | 589/3998 [00:23<01:49, 31.04it/s]

Running loglikelihood requests:  15%|█▌        | 600/3998 [00:23<01:39, 34.13it/s]

Running loglikelihood requests:  15%|█▌        | 608/3998 [00:24<01:42, 32.99it/s]

Running loglikelihood requests:  15%|█▌        | 616/3998 [00:24<01:44, 32.25it/s]

Running loglikelihood requests:  16%|█▌        | 624/3998 [00:24<01:46, 31.71it/s]

Running loglikelihood requests:  16%|█▌        | 632/3998 [00:24<01:47, 31.44it/s]

Running loglikelihood requests:  16%|█▌        | 643/3998 [00:25<01:37, 34.59it/s]

Running loglikelihood requests:  16%|█▋        | 651/3998 [00:25<01:40, 33.37it/s]

Running loglikelihood requests:  16%|█▋        | 659/3998 [00:25<01:42, 32.49it/s]

Running loglikelihood requests:  17%|█▋        | 667/3998 [00:25<01:44, 31.93it/s]

Running loglikelihood requests:  17%|█▋        | 675/3998 [00:26<01:45, 31.50it/s]

Running loglikelihood requests:  17%|█▋        | 683/3998 [00:26<01:45, 31.35it/s]

Running loglikelihood requests:  17%|█▋        | 691/3998 [00:26<01:45, 31.35it/s]

Running loglikelihood requests:  17%|█▋        | 699/3998 [00:27<01:45, 31.17it/s]

Running loglikelihood requests:  18%|█▊        | 707/3998 [00:27<01:46, 30.97it/s]

Running loglikelihood requests:  18%|█▊        | 715/3998 [00:27<01:46, 30.95it/s]

Running loglikelihood requests:  18%|█▊        | 723/3998 [00:27<01:46, 30.86it/s]

Running loglikelihood requests:  18%|█▊        | 731/3998 [00:28<01:45, 30.94it/s]

Running loglikelihood requests:  18%|█▊        | 739/3998 [00:28<01:45, 30.94it/s]

Running loglikelihood requests:  19%|█▊        | 747/3998 [00:28<01:45, 30.88it/s]

Running loglikelihood requests:  19%|█▉        | 755/3998 [00:28<01:45, 30.84it/s]

Running loglikelihood requests:  19%|█▉        | 763/3998 [00:29<01:45, 30.77it/s]

Running loglikelihood requests:  19%|█▉        | 771/3998 [00:29<01:44, 30.86it/s]

Running loglikelihood requests:  19%|█▉        | 779/3998 [00:29<01:41, 31.72it/s]

Running loglikelihood requests:  20%|█▉        | 787/3998 [00:29<01:39, 32.35it/s]

Running loglikelihood requests:  20%|█▉        | 796/3998 [00:30<01:33, 34.13it/s]

Running loglikelihood requests:  20%|██        | 804/3998 [00:30<01:33, 34.01it/s]

Running loglikelihood requests:  20%|██        | 812/3998 [00:30<01:33, 33.97it/s]

Running loglikelihood requests:  21%|██        | 820/3998 [00:30<01:32, 34.18it/s]

Running loglikelihood requests:  21%|██        | 828/3998 [00:30<01:33, 34.06it/s]

Running loglikelihood requests:  21%|██        | 836/3998 [00:31<01:32, 34.04it/s]

Running loglikelihood requests:  21%|██        | 844/3998 [00:31<01:32, 34.09it/s]

Running loglikelihood requests:  21%|██▏       | 852/3998 [00:31<01:32, 34.12it/s]

Running loglikelihood requests:  22%|██▏       | 860/3998 [00:31<01:31, 34.25it/s]

Running loglikelihood requests:  22%|██▏       | 868/3998 [00:32<01:31, 34.26it/s]

Running loglikelihood requests:  22%|██▏       | 876/3998 [00:32<01:30, 34.36it/s]

Running loglikelihood requests:  22%|██▏       | 884/3998 [00:32<01:30, 34.34it/s]

Running loglikelihood requests:  22%|██▏       | 892/3998 [00:32<01:30, 34.46it/s]

Running loglikelihood requests:  23%|██▎       | 900/3998 [00:33<01:29, 34.50it/s]

Running loglikelihood requests:  23%|██▎       | 908/3998 [00:33<01:29, 34.37it/s]

Running loglikelihood requests:  23%|██▎       | 916/3998 [00:33<01:29, 34.46it/s]

Running loglikelihood requests:  23%|██▎       | 924/3998 [00:33<01:29, 34.50it/s]

Running loglikelihood requests:  23%|██▎       | 932/3998 [00:34<01:28, 34.61it/s]

Running loglikelihood requests:  24%|██▎       | 940/3998 [00:34<01:28, 34.54it/s]

Running loglikelihood requests:  24%|██▎       | 948/3998 [00:34<01:28, 34.64it/s]

Running loglikelihood requests:  24%|██▍       | 956/3998 [00:34<01:27, 34.85it/s]

Running loglikelihood requests:  24%|██▍       | 964/3998 [00:34<01:27, 34.73it/s]

Running loglikelihood requests:  24%|██▍       | 972/3998 [00:35<01:26, 34.82it/s]

Running loglikelihood requests:  25%|██▍       | 980/3998 [00:35<01:26, 34.89it/s]

Running loglikelihood requests:  25%|██▍       | 988/3998 [00:35<01:26, 34.65it/s]

Running loglikelihood requests:  25%|██▍       | 996/3998 [00:35<01:26, 34.80it/s]

Running loglikelihood requests:  25%|██▌       | 1004/3998 [00:36<01:25, 35.01it/s]

Running loglikelihood requests:  25%|██▌       | 1012/3998 [00:36<01:25, 34.74it/s]

Running loglikelihood requests:  26%|██▌       | 1020/3998 [00:36<01:25, 34.87it/s]

Running loglikelihood requests:  26%|██▌       | 1028/3998 [00:36<01:25, 34.79it/s]

Running loglikelihood requests:  26%|██▌       | 1036/3998 [00:36<01:25, 34.83it/s]

Running loglikelihood requests:  26%|██▌       | 1044/3998 [00:37<01:24, 34.91it/s]

Running loglikelihood requests:  26%|██▋       | 1053/3998 [00:37<01:21, 36.07it/s]

Running loglikelihood requests:  27%|██▋       | 1061/3998 [00:37<01:22, 35.77it/s]

Running loglikelihood requests:  27%|██▋       | 1069/3998 [00:37<01:22, 35.51it/s]

Running loglikelihood requests:  27%|██▋       | 1077/3998 [00:38<01:23, 35.19it/s]

Running loglikelihood requests:  27%|██▋       | 1085/3998 [00:38<01:22, 35.23it/s]

Running loglikelihood requests:  27%|██▋       | 1093/3998 [00:38<01:22, 35.22it/s]

Running loglikelihood requests:  28%|██▊       | 1101/3998 [00:38<01:22, 35.13it/s]

Running loglikelihood requests:  28%|██▊       | 1109/3998 [00:39<01:22, 35.22it/s]

Running loglikelihood requests:  28%|██▊       | 1117/3998 [00:39<01:21, 35.32it/s]

Running loglikelihood requests:  28%|██▊       | 1128/3998 [00:39<01:13, 39.07it/s]

Running loglikelihood requests:  28%|██▊       | 1136/3998 [00:39<01:15, 37.67it/s]

Running loglikelihood requests:  29%|██▊       | 1144/3998 [00:39<01:17, 36.95it/s]

Running loglikelihood requests:  29%|██▉       | 1152/3998 [00:40<01:18, 36.46it/s]

Running loglikelihood requests:  29%|██▉       | 1160/3998 [00:40<01:18, 35.98it/s]

Running loglikelihood requests:  29%|██▉       | 1168/3998 [00:40<01:18, 35.89it/s]

Running loglikelihood requests:  29%|██▉       | 1176/3998 [00:40<01:18, 35.85it/s]

Running loglikelihood requests:  30%|██▉       | 1184/3998 [00:41<01:18, 35.78it/s]

Running loglikelihood requests:  30%|██▉       | 1192/3998 [00:41<01:18, 35.66it/s]

Running loglikelihood requests:  30%|███       | 1204/3998 [00:41<01:08, 40.66it/s]

Running loglikelihood requests:  30%|███       | 1215/3998 [00:41<01:04, 43.10it/s]

Running loglikelihood requests:  31%|███       | 1223/3998 [00:41<01:08, 40.80it/s]

Running loglikelihood requests:  31%|███       | 1231/3998 [00:42<01:10, 39.37it/s]

Running loglikelihood requests:  31%|███       | 1239/3998 [00:42<01:12, 38.24it/s]

Running loglikelihood requests:  31%|███       | 1247/3998 [00:42<01:13, 37.41it/s]

Running loglikelihood requests:  31%|███▏      | 1255/3998 [00:42<01:14, 36.92it/s]

Running loglikelihood requests:  32%|███▏      | 1263/3998 [00:43<01:15, 36.42it/s]

Running loglikelihood requests:  32%|███▏      | 1271/3998 [00:43<01:15, 36.09it/s]

Running loglikelihood requests:  32%|███▏      | 1279/3998 [00:43<01:15, 36.04it/s]

Running loglikelihood requests:  32%|███▏      | 1287/3998 [00:43<01:15, 35.98it/s]

Running loglikelihood requests:  32%|███▏      | 1295/3998 [00:44<01:15, 36.02it/s]

Running loglikelihood requests:  33%|███▎      | 1303/3998 [00:44<01:15, 35.91it/s]

Running loglikelihood requests:  33%|███▎      | 1311/3998 [00:44<01:14, 35.89it/s]

Running loglikelihood requests:  33%|███▎      | 1319/3998 [00:44<01:14, 35.84it/s]

Running loglikelihood requests:  33%|███▎      | 1327/3998 [00:44<01:14, 36.00it/s]

Running loglikelihood requests:  33%|███▎      | 1335/3998 [00:45<01:14, 35.95it/s]

Running loglikelihood requests:  34%|███▎      | 1343/3998 [00:45<01:13, 36.02it/s]

Running loglikelihood requests:  34%|███▍      | 1351/3998 [00:45<01:14, 35.71it/s]

Running loglikelihood requests:  34%|███▍      | 1359/3998 [00:45<01:14, 35.62it/s]

Running loglikelihood requests:  34%|███▍      | 1367/3998 [00:46<01:13, 35.59it/s]

Running loglikelihood requests:  34%|███▍      | 1375/3998 [00:46<01:14, 35.34it/s]

Running loglikelihood requests:  35%|███▍      | 1383/3998 [00:46<01:13, 35.38it/s]

Running loglikelihood requests:  35%|███▍      | 1393/3998 [00:46<01:08, 38.07it/s]

Running loglikelihood requests:  35%|███▌      | 1401/3998 [00:46<01:09, 37.26it/s]

Running loglikelihood requests:  35%|███▌      | 1411/3998 [00:47<01:06, 39.09it/s]

Running loglikelihood requests:  35%|███▌      | 1419/3998 [00:47<01:07, 38.07it/s]

Running loglikelihood requests:  36%|███▌      | 1427/3998 [00:47<01:09, 37.23it/s]

Running loglikelihood requests:  36%|███▌      | 1435/3998 [00:47<01:09, 36.78it/s]

Running loglikelihood requests:  36%|███▌      | 1443/3998 [00:48<01:10, 36.32it/s]

Running loglikelihood requests:  36%|███▋      | 1451/3998 [00:48<01:11, 35.83it/s]

Running loglikelihood requests:  36%|███▋      | 1459/3998 [00:48<01:10, 35.80it/s]

Running loglikelihood requests:  37%|███▋      | 1467/3998 [00:48<01:10, 35.91it/s]

Running loglikelihood requests:  37%|███▋      | 1475/3998 [00:48<01:10, 35.86it/s]

Running loglikelihood requests:  37%|███▋      | 1483/3998 [00:49<01:10, 35.76it/s]

Running loglikelihood requests:  37%|███▋      | 1491/3998 [00:49<01:10, 35.81it/s]

Running loglikelihood requests:  37%|███▋      | 1499/3998 [00:49<01:10, 35.68it/s]

Running loglikelihood requests:  38%|███▊      | 1511/3998 [00:49<01:01, 40.67it/s]

Running loglikelihood requests:  38%|███▊      | 1519/3998 [00:50<01:03, 39.10it/s]

Running loglikelihood requests:  38%|███▊      | 1527/3998 [00:50<01:04, 38.04it/s]

Running loglikelihood requests:  38%|███▊      | 1535/3998 [00:50<01:05, 37.46it/s]

Running loglikelihood requests:  39%|███▊      | 1543/3998 [00:50<01:06, 36.86it/s]

Running loglikelihood requests:  39%|███▉      | 1551/3998 [00:50<01:07, 36.49it/s]

Running loglikelihood requests:  39%|███▉      | 1559/3998 [00:51<01:07, 36.25it/s]

Running loglikelihood requests:  39%|███▉      | 1567/3998 [00:51<01:07, 35.86it/s]

Running loglikelihood requests:  39%|███▉      | 1575/3998 [00:51<01:07, 35.67it/s]

Running loglikelihood requests:  40%|███▉      | 1583/3998 [00:51<01:07, 35.62it/s]

Running loglikelihood requests:  40%|███▉      | 1591/3998 [00:52<01:07, 35.54it/s]

Running loglikelihood requests:  40%|███▉      | 1599/3998 [00:52<01:07, 35.51it/s]

Running loglikelihood requests:  40%|████      | 1607/3998 [00:52<01:07, 35.25it/s]

Running loglikelihood requests:  40%|████      | 1615/3998 [00:52<01:07, 35.31it/s]

Running loglikelihood requests:  41%|████      | 1623/3998 [00:53<01:07, 35.05it/s]

Running loglikelihood requests:  41%|████      | 1631/3998 [00:53<01:07, 35.10it/s]

Running loglikelihood requests:  41%|████      | 1639/3998 [00:53<01:07, 35.20it/s]

Running loglikelihood requests:  41%|████      | 1647/3998 [00:53<01:06, 35.35it/s]

Running loglikelihood requests:  41%|████▏     | 1655/3998 [00:53<01:06, 35.43it/s]

Running loglikelihood requests:  42%|████▏     | 1663/3998 [00:54<01:05, 35.53it/s]

Running loglikelihood requests:  42%|████▏     | 1671/3998 [00:54<01:05, 35.52it/s]

Running loglikelihood requests:  42%|████▏     | 1679/3998 [00:54<01:05, 35.44it/s]

Running loglikelihood requests:  42%|████▏     | 1687/3998 [00:54<01:05, 35.50it/s]

Running loglikelihood requests:  42%|████▏     | 1695/3998 [00:55<01:04, 35.65it/s]

Running loglikelihood requests:  43%|████▎     | 1705/3998 [00:55<00:59, 38.26it/s]

Running loglikelihood requests:  43%|████▎     | 1713/3998 [00:55<01:01, 37.39it/s]

Running loglikelihood requests:  43%|████▎     | 1721/3998 [00:55<01:01, 36.90it/s]

Running loglikelihood requests:  43%|████▎     | 1731/3998 [00:55<00:57, 39.34it/s]

Running loglikelihood requests:  44%|████▎     | 1740/3998 [00:56<00:57, 39.53it/s]

Running loglikelihood requests:  44%|████▎     | 1748/3998 [00:56<00:58, 38.34it/s]

Running loglikelihood requests:  44%|████▍     | 1756/3998 [00:56<00:59, 37.55it/s]

Running loglikelihood requests:  44%|████▍     | 1764/3998 [00:56<01:00, 36.90it/s]

Running loglikelihood requests:  44%|████▍     | 1772/3998 [00:57<01:01, 36.46it/s]

Running loglikelihood requests:  45%|████▍     | 1780/3998 [00:57<01:01, 36.24it/s]

Running loglikelihood requests:  45%|████▍     | 1788/3998 [00:57<01:01, 36.14it/s]

Running loglikelihood requests:  45%|████▍     | 1796/3998 [00:57<01:01, 35.97it/s]

Running loglikelihood requests:  45%|████▌     | 1804/3998 [00:57<01:00, 36.05it/s]

Running loglikelihood requests:  45%|████▌     | 1812/3998 [00:58<01:00, 36.01it/s]

Running loglikelihood requests:  46%|████▌     | 1820/3998 [00:58<01:00, 36.03it/s]

Running loglikelihood requests:  46%|████▌     | 1831/3998 [00:58<00:54, 40.08it/s]

Running loglikelihood requests:  46%|████▌     | 1842/3998 [00:58<00:50, 42.70it/s]

Running loglikelihood requests:  46%|████▋     | 1850/3998 [00:59<00:52, 40.75it/s]

Running loglikelihood requests:  46%|████▋     | 1858/3998 [00:59<00:54, 39.36it/s]

Running loglikelihood requests:  47%|████▋     | 1867/3998 [00:59<00:53, 39.74it/s]

Running loglikelihood requests:  47%|████▋     | 1875/3998 [00:59<00:55, 38.46it/s]

Running loglikelihood requests:  47%|████▋     | 1883/3998 [00:59<00:56, 37.73it/s]

Running loglikelihood requests:  47%|████▋     | 1891/3998 [01:00<00:56, 37.24it/s]

Running loglikelihood requests:  47%|████▋     | 1899/3998 [01:00<00:57, 36.81it/s]

Running loglikelihood requests:  48%|████▊     | 1907/3998 [01:00<00:57, 36.50it/s]

Running loglikelihood requests:  48%|████▊     | 1915/3998 [01:00<00:57, 36.31it/s]

Running loglikelihood requests:  48%|████▊     | 1923/3998 [01:01<00:57, 36.16it/s]

Running loglikelihood requests:  48%|████▊     | 1931/3998 [01:01<00:57, 35.99it/s]

Running loglikelihood requests:  48%|████▊     | 1939/3998 [01:01<00:57, 36.03it/s]

Running loglikelihood requests:  49%|████▊     | 1947/3998 [01:01<00:56, 36.08it/s]

Running loglikelihood requests:  49%|████▉     | 1957/3998 [01:01<00:52, 38.76it/s]

Running loglikelihood requests:  49%|████▉     | 1965/3998 [01:02<00:53, 37.96it/s]

Running loglikelihood requests:  49%|████▉     | 1973/3998 [01:02<00:54, 37.38it/s]

Running loglikelihood requests:  50%|████▉     | 1981/3998 [01:02<00:54, 37.07it/s]

Running loglikelihood requests:  50%|████▉     | 1989/3998 [01:02<00:54, 36.68it/s]

Running loglikelihood requests:  50%|████▉     | 1997/3998 [01:03<00:54, 36.46it/s]

Running loglikelihood requests:  50%|█████     | 2005/3998 [01:03<00:54, 36.28it/s]

Running loglikelihood requests:  50%|█████     | 2013/3998 [01:03<00:54, 36.34it/s]

Running loglikelihood requests:  51%|█████     | 2021/3998 [01:03<00:54, 36.22it/s]

Running loglikelihood requests:  51%|█████     | 2029/3998 [01:03<00:54, 36.09it/s]

Running loglikelihood requests:  51%|█████     | 2037/3998 [01:04<00:54, 35.99it/s]

Running loglikelihood requests:  51%|█████     | 2045/3998 [01:04<00:54, 35.98it/s]

Running loglikelihood requests:  51%|█████▏    | 2053/3998 [01:04<00:54, 35.97it/s]

Running loglikelihood requests:  52%|█████▏    | 2061/3998 [01:04<00:53, 35.97it/s]

Running loglikelihood requests:  52%|█████▏    | 2069/3998 [01:05<00:53, 36.04it/s]

Running loglikelihood requests:  52%|█████▏    | 2079/3998 [01:05<00:49, 38.61it/s]

Running loglikelihood requests:  52%|█████▏    | 2087/3998 [01:05<00:50, 37.86it/s]

Running loglikelihood requests:  52%|█████▏    | 2095/3998 [01:05<00:51, 37.14it/s]

Running loglikelihood requests:  53%|█████▎    | 2103/3998 [01:05<00:51, 36.86it/s]

Running loglikelihood requests:  53%|█████▎    | 2111/3998 [01:06<00:51, 36.43it/s]

Running loglikelihood requests:  53%|█████▎    | 2119/3998 [01:06<00:51, 36.48it/s]

Running loglikelihood requests:  53%|█████▎    | 2127/3998 [01:06<00:51, 36.38it/s]

Running loglikelihood requests:  53%|█████▎    | 2136/3998 [01:06<00:49, 37.61it/s]

Running loglikelihood requests:  54%|█████▎    | 2144/3998 [01:07<00:49, 37.34it/s]

Running loglikelihood requests:  54%|█████▍    | 2152/3998 [01:07<00:50, 36.86it/s]

Running loglikelihood requests:  54%|█████▍    | 2160/3998 [01:07<00:50, 36.76it/s]

Running loglikelihood requests:  54%|█████▍    | 2171/3998 [01:07<00:44, 40.76it/s]

Running loglikelihood requests:  55%|█████▍    | 2179/3998 [01:07<00:45, 39.62it/s]

Running loglikelihood requests:  55%|█████▍    | 2187/3998 [01:08<00:46, 38.66it/s]

Running loglikelihood requests:  55%|█████▍    | 2195/3998 [01:08<00:47, 38.08it/s]

Running loglikelihood requests:  55%|█████▌    | 2203/3998 [01:08<00:47, 37.55it/s]

Running loglikelihood requests:  55%|█████▌    | 2211/3998 [01:08<00:48, 37.12it/s]

Running loglikelihood requests:  56%|█████▌    | 2219/3998 [01:09<00:46, 38.67it/s]

Running loglikelihood requests:  56%|█████▌    | 2227/3998 [01:09<00:44, 40.00it/s]

Running loglikelihood requests:  56%|█████▌    | 2235/3998 [01:09<00:43, 40.96it/s]

Running loglikelihood requests:  56%|█████▌    | 2243/3998 [01:09<00:42, 41.54it/s]

Running loglikelihood requests:  56%|█████▋    | 2251/3998 [01:09<00:41, 41.81it/s]

Running loglikelihood requests:  57%|█████▋    | 2259/3998 [01:09<00:41, 41.76it/s]

Running loglikelihood requests:  57%|█████▋    | 2268/3998 [01:10<00:39, 43.48it/s]

Running loglikelihood requests:  57%|█████▋    | 2281/3998 [01:10<00:33, 51.45it/s]

Running loglikelihood requests:  57%|█████▋    | 2289/3998 [01:10<00:34, 48.89it/s]

Running loglikelihood requests:  58%|█████▊    | 2300/3998 [01:10<00:32, 51.55it/s]

Running loglikelihood requests:  58%|█████▊    | 2308/3998 [01:10<00:34, 49.21it/s]

Running loglikelihood requests:  58%|█████▊    | 2316/3998 [01:11<00:35, 47.52it/s]

Running loglikelihood requests:  58%|█████▊    | 2324/3998 [01:11<00:36, 46.46it/s]

Running loglikelihood requests:  58%|█████▊    | 2332/3998 [01:11<00:36, 45.73it/s]

Running loglikelihood requests:  59%|█████▊    | 2340/3998 [01:11<00:36, 45.03it/s]

Running loglikelihood requests:  59%|█████▊    | 2348/3998 [01:11<00:37, 44.18it/s]

Running loglikelihood requests:  59%|█████▉    | 2357/3998 [01:12<00:36, 45.51it/s]

Running loglikelihood requests:  59%|█████▉    | 2367/3998 [01:12<00:33, 48.18it/s]

Running loglikelihood requests:  59%|█████▉    | 2375/3998 [01:12<00:35, 46.35it/s]

Running loglikelihood requests:  60%|█████▉    | 2384/3998 [01:12<00:34, 46.99it/s]

Running loglikelihood requests:  60%|█████▉    | 2396/3998 [01:12<00:30, 51.96it/s]

Running loglikelihood requests:  60%|██████    | 2404/3998 [01:12<00:32, 49.42it/s]

Running loglikelihood requests:  60%|██████    | 2412/3998 [01:13<00:33, 47.66it/s]

Running loglikelihood requests:  61%|██████    | 2420/3998 [01:13<00:34, 46.09it/s]

Running loglikelihood requests:  61%|██████    | 2428/3998 [01:13<00:34, 45.26it/s]

Running loglikelihood requests:  61%|██████    | 2439/3998 [01:13<00:31, 49.69it/s]

Running loglikelihood requests:  61%|██████    | 2447/3998 [01:13<00:32, 47.89it/s]

Running loglikelihood requests:  61%|██████▏   | 2455/3998 [01:14<00:33, 46.62it/s]

Running loglikelihood requests:  62%|██████▏   | 2466/3998 [01:14<00:30, 50.73it/s]

Running loglikelihood requests:  62%|██████▏   | 2474/3998 [01:14<00:31, 48.84it/s]

Running loglikelihood requests:  62%|██████▏   | 2482/3998 [01:14<00:31, 47.40it/s]

Running loglikelihood requests:  62%|██████▏   | 2490/3998 [01:14<00:32, 46.23it/s]

Running loglikelihood requests:  62%|██████▏   | 2498/3998 [01:14<00:32, 45.65it/s]

Running loglikelihood requests:  63%|██████▎   | 2506/3998 [01:15<00:33, 45.04it/s]

Running loglikelihood requests:  63%|██████▎   | 2514/3998 [01:15<00:33, 44.74it/s]

Running loglikelihood requests:  63%|██████▎   | 2522/3998 [01:15<00:33, 44.46it/s]

Running loglikelihood requests:  63%|██████▎   | 2530/3998 [01:15<00:33, 43.85it/s]

Running loglikelihood requests:  63%|██████▎   | 2538/3998 [01:15<00:33, 44.12it/s]

Running loglikelihood requests:  64%|██████▎   | 2546/3998 [01:16<00:33, 43.90it/s]

Running loglikelihood requests:  64%|██████▍   | 2556/3998 [01:16<00:30, 46.90it/s]

Running loglikelihood requests:  64%|██████▍   | 2567/3998 [01:16<00:28, 50.62it/s]

Running loglikelihood requests:  64%|██████▍   | 2576/3998 [01:16<00:28, 50.01it/s]

Running loglikelihood requests:  65%|██████▍   | 2584/3998 [01:16<00:29, 47.75it/s]

Running loglikelihood requests:  65%|██████▍   | 2595/3998 [01:16<00:27, 51.44it/s]

Running loglikelihood requests:  65%|██████▌   | 2603/3998 [01:17<00:28, 48.96it/s]

Running loglikelihood requests:  65%|██████▌   | 2612/3998 [01:17<00:28, 48.85it/s]

Running loglikelihood requests:  66%|██████▌   | 2623/3998 [01:17<00:26, 52.16it/s]

Running loglikelihood requests:  66%|██████▌   | 2631/3998 [01:17<00:27, 49.11it/s]

Running loglikelihood requests:  66%|██████▌   | 2639/3998 [01:17<00:29, 46.33it/s]

Running loglikelihood requests:  66%|██████▌   | 2647/3998 [01:18<00:29, 45.21it/s]

Running loglikelihood requests:  66%|██████▋   | 2655/3998 [01:18<00:30, 44.60it/s]

Running loglikelihood requests:  67%|██████▋   | 2664/3998 [01:18<00:28, 46.02it/s]

Running loglikelihood requests:  67%|██████▋   | 2672/3998 [01:18<00:29, 45.55it/s]

Running loglikelihood requests:  67%|██████▋   | 2682/3998 [01:18<00:27, 48.52it/s]

Running loglikelihood requests:  67%|██████▋   | 2690/3998 [01:19<00:27, 47.43it/s]

Running loglikelihood requests:  67%|██████▋   | 2698/3998 [01:19<00:28, 46.07it/s]

Running loglikelihood requests:  68%|██████▊   | 2711/3998 [01:19<00:23, 54.25it/s]

Running loglikelihood requests:  68%|██████▊   | 2719/3998 [01:19<00:25, 50.96it/s]

Running loglikelihood requests:  68%|██████▊   | 2727/3998 [01:19<00:26, 48.61it/s]

Running loglikelihood requests:  68%|██████▊   | 2735/3998 [01:19<00:26, 47.17it/s]

Running loglikelihood requests:  69%|██████▊   | 2743/3998 [01:20<00:27, 46.28it/s]

Running loglikelihood requests:  69%|██████▉   | 2751/3998 [01:20<00:27, 45.42it/s]

Running loglikelihood requests:  69%|██████▉   | 2759/3998 [01:20<00:27, 44.95it/s]

Running loglikelihood requests:  69%|██████▉   | 2767/3998 [01:20<00:27, 44.95it/s]

Running loglikelihood requests:  69%|██████▉   | 2775/3998 [01:20<00:27, 44.57it/s]

Running loglikelihood requests:  70%|██████▉   | 2786/3998 [01:21<00:24, 49.25it/s]

Running loglikelihood requests:  70%|██████▉   | 2794/3998 [01:21<00:25, 47.51it/s]

Running loglikelihood requests:  70%|███████   | 2802/3998 [01:21<00:25, 46.48it/s]

Running loglikelihood requests:  70%|███████   | 2810/3998 [01:21<00:25, 45.87it/s]

Running loglikelihood requests:  70%|███████   | 2818/3998 [01:21<00:25, 45.61it/s]

Running loglikelihood requests:  71%|███████   | 2826/3998 [01:21<00:26, 44.48it/s]

Running loglikelihood requests:  71%|███████   | 2834/3998 [01:22<00:26, 44.20it/s]

Running loglikelihood requests:  71%|███████   | 2842/3998 [01:22<00:25, 44.48it/s]

Running loglikelihood requests:  71%|███████▏  | 2853/3998 [01:22<00:23, 49.33it/s]

Running loglikelihood requests:  72%|███████▏  | 2861/3998 [01:22<00:23, 47.94it/s]

Running loglikelihood requests:  72%|███████▏  | 2869/3998 [01:22<00:24, 46.69it/s]

Running loglikelihood requests:  72%|███████▏  | 2880/3998 [01:23<00:21, 51.06it/s]

Running loglikelihood requests:  72%|███████▏  | 2888/3998 [01:23<00:22, 49.03it/s]

Running loglikelihood requests:  72%|███████▏  | 2896/3998 [01:23<00:23, 47.79it/s]

Running loglikelihood requests:  73%|███████▎  | 2904/3998 [01:23<00:23, 47.20it/s]

Running loglikelihood requests:  73%|███████▎  | 2915/3998 [01:23<00:20, 51.65it/s]

Running loglikelihood requests:  73%|███████▎  | 2923/3998 [01:23<00:21, 49.31it/s]

Running loglikelihood requests:  73%|███████▎  | 2931/3998 [01:24<00:22, 47.40it/s]

Running loglikelihood requests:  74%|███████▎  | 2939/3998 [01:24<00:22, 46.83it/s]

Running loglikelihood requests:  74%|███████▎  | 2947/3998 [01:24<00:22, 46.05it/s]

Running loglikelihood requests:  74%|███████▍  | 2955/3998 [01:24<00:22, 45.75it/s]

Running loglikelihood requests:  74%|███████▍  | 2963/3998 [01:24<00:22, 45.59it/s]

Running loglikelihood requests:  74%|███████▍  | 2971/3998 [01:25<00:22, 45.38it/s]

Running loglikelihood requests:  75%|███████▍  | 2979/3998 [01:25<00:22, 45.18it/s]

Running loglikelihood requests:  75%|███████▍  | 2987/3998 [01:25<00:22, 45.01it/s]

Running loglikelihood requests:  75%|███████▍  | 2995/3998 [01:25<00:22, 44.83it/s]

Running loglikelihood requests:  75%|███████▌  | 3006/3998 [01:25<00:19, 49.84it/s]

Running loglikelihood requests:  75%|███████▌  | 3014/3998 [01:25<00:20, 48.53it/s]

Running loglikelihood requests:  76%|███████▌  | 3022/3998 [01:26<00:20, 47.53it/s]

Running loglikelihood requests:  76%|███████▌  | 3030/3998 [01:26<00:20, 47.02it/s]

Running loglikelihood requests:  76%|███████▌  | 3038/3998 [01:26<00:20, 46.78it/s]

Running loglikelihood requests:  76%|███████▌  | 3046/3998 [01:26<00:20, 46.76it/s]

Running loglikelihood requests:  76%|███████▋  | 3057/3998 [01:26<00:18, 51.71it/s]

Running loglikelihood requests:  77%|███████▋  | 3065/3998 [01:26<00:18, 50.20it/s]

Running loglikelihood requests:  77%|███████▋  | 3075/3998 [01:27<00:17, 52.05it/s]

Running loglikelihood requests:  77%|███████▋  | 3083/3998 [01:27<00:18, 50.49it/s]

Running loglikelihood requests:  77%|███████▋  | 3091/3998 [01:27<00:18, 48.97it/s]

Running loglikelihood requests:  78%|███████▊  | 3099/3998 [01:27<00:18, 47.60it/s]

Running loglikelihood requests:  78%|███████▊  | 3107/3998 [01:27<00:18, 47.14it/s]

Running loglikelihood requests:  78%|███████▊  | 3115/3998 [01:27<00:18, 46.78it/s]

Running loglikelihood requests:  78%|███████▊  | 3123/3998 [01:28<00:20, 41.87it/s]

Running loglikelihood requests:  78%|███████▊  | 3131/3998 [01:28<00:20, 43.28it/s]

Running loglikelihood requests:  79%|███████▊  | 3139/3998 [01:28<00:19, 43.91it/s]

Running loglikelihood requests:  79%|███████▉  | 3151/3998 [01:28<00:16, 50.85it/s]

Running loglikelihood requests:  79%|███████▉  | 3163/3998 [01:28<00:14, 55.86it/s]

Running loglikelihood requests:  79%|███████▉  | 3177/3998 [01:29<00:13, 63.15it/s]

Running loglikelihood requests:  80%|███████▉  | 3189/3998 [01:29<00:12, 64.28it/s]

Running loglikelihood requests:  80%|███████▉  | 3197/3998 [01:29<00:13, 58.79it/s]

Running loglikelihood requests:  80%|████████  | 3205/3998 [01:29<00:14, 54.77it/s]

Running loglikelihood requests:  80%|████████  | 3218/3998 [01:29<00:12, 60.64it/s]

Running loglikelihood requests:  81%|████████  | 3226/3998 [01:29<00:13, 56.25it/s]

Running loglikelihood requests:  81%|████████  | 3234/3998 [01:30<00:14, 52.03it/s]

Running loglikelihood requests:  81%|████████  | 3242/3998 [01:30<00:15, 48.47it/s]

Running loglikelihood requests:  81%|████████▏ | 3250/3998 [01:30<00:15, 47.83it/s]

Running loglikelihood requests:  81%|████████▏ | 3258/3998 [01:30<00:15, 47.52it/s]

Running loglikelihood requests:  82%|████████▏ | 3266/3998 [01:30<00:15, 47.71it/s]

Running loglikelihood requests:  82%|████████▏ | 3274/3998 [01:31<00:15, 47.71it/s]

Running loglikelihood requests:  82%|████████▏ | 3282/3998 [01:31<00:15, 47.36it/s]

Running loglikelihood requests:  82%|████████▏ | 3290/3998 [01:31<00:15, 47.11it/s]

Running loglikelihood requests:  83%|████████▎ | 3299/3998 [01:31<00:14, 48.52it/s]

Running loglikelihood requests:  83%|████████▎ | 3307/3998 [01:31<00:14, 47.49it/s]

Running loglikelihood requests:  83%|████████▎ | 3315/3998 [01:31<00:14, 46.89it/s]

Running loglikelihood requests:  83%|████████▎ | 3323/3998 [01:32<00:14, 46.81it/s]

Running loglikelihood requests:  83%|████████▎ | 3331/3998 [01:32<00:14, 46.75it/s]

Running loglikelihood requests:  84%|████████▎ | 3342/3998 [01:32<00:12, 51.86it/s]

Running loglikelihood requests:  84%|████████▍ | 3353/3998 [01:32<00:11, 55.53it/s]

Running loglikelihood requests:  84%|████████▍ | 3364/3998 [01:32<00:10, 58.29it/s]

Running loglikelihood requests:  84%|████████▍ | 3373/3998 [01:32<00:11, 56.19it/s]

Running loglikelihood requests:  85%|████████▍ | 3383/3998 [01:33<00:10, 56.72it/s]

Running loglikelihood requests:  85%|████████▍ | 3391/3998 [01:33<00:11, 53.86it/s]

Running loglikelihood requests:  85%|████████▌ | 3401/3998 [01:33<00:10, 55.26it/s]

Running loglikelihood requests:  85%|████████▌ | 3410/3998 [01:33<00:10, 54.33it/s]

Running loglikelihood requests:  86%|████████▌ | 3421/3998 [01:33<00:10, 57.35it/s]

Running loglikelihood requests:  86%|████████▌ | 3432/3998 [01:33<00:09, 58.94it/s]

Running loglikelihood requests:  86%|████████▌ | 3440/3998 [01:34<00:09, 56.24it/s]

Running loglikelihood requests:  86%|████████▋ | 3450/3998 [01:34<00:09, 56.94it/s]

Running loglikelihood requests:  86%|████████▋ | 3458/3998 [01:34<00:10, 53.54it/s]

Running loglikelihood requests:  87%|████████▋ | 3469/3998 [01:34<00:09, 57.09it/s]

Running loglikelihood requests:  87%|████████▋ | 3480/3998 [01:34<00:08, 59.81it/s]

Running loglikelihood requests:  87%|████████▋ | 3488/3998 [01:34<00:09, 56.01it/s]

Running loglikelihood requests:  88%|████████▊ | 3500/3998 [01:35<00:08, 60.97it/s]

Running loglikelihood requests:  88%|████████▊ | 3508/3998 [01:35<00:08, 56.36it/s]

Running loglikelihood requests:  88%|████████▊ | 3516/3998 [01:35<00:09, 53.44it/s]

Running loglikelihood requests:  88%|████████▊ | 3524/3998 [01:35<00:09, 51.35it/s]

Running loglikelihood requests:  88%|████████▊ | 3532/3998 [01:35<00:09, 50.30it/s]

Running loglikelihood requests:  89%|████████▊ | 3540/3998 [01:36<00:09, 49.48it/s]

Running loglikelihood requests:  89%|████████▊ | 3548/3998 [01:36<00:09, 48.68it/s]

Running loglikelihood requests:  89%|████████▉ | 3559/3998 [01:36<00:08, 53.54it/s]

Running loglikelihood requests:  89%|████████▉ | 3567/3998 [01:36<00:08, 51.90it/s]

Running loglikelihood requests:  89%|████████▉ | 3575/3998 [01:36<00:08, 51.15it/s]

Running loglikelihood requests:  90%|████████▉ | 3588/3998 [01:36<00:07, 58.27it/s]

Running loglikelihood requests:  90%|████████▉ | 3596/3998 [01:37<00:07, 55.53it/s]

Running loglikelihood requests:  90%|█████████ | 3604/3998 [01:37<00:07, 53.49it/s]

Running loglikelihood requests:  90%|█████████ | 3613/3998 [01:37<00:07, 53.46it/s]

Running loglikelihood requests:  91%|█████████ | 3621/3998 [01:37<00:07, 52.14it/s]

Running loglikelihood requests:  91%|█████████ | 3631/3998 [01:37<00:06, 54.56it/s]

Running loglikelihood requests:  91%|█████████ | 3642/3998 [01:37<00:06, 58.24it/s]

Running loglikelihood requests:  91%|█████████▏| 3653/3998 [01:38<00:05, 60.63it/s]

Running loglikelihood requests:  92%|█████████▏| 3663/3998 [01:38<00:05, 60.76it/s]

Running loglikelihood requests:  92%|█████████▏| 3671/3998 [01:38<00:05, 56.67it/s]

Running loglikelihood requests:  92%|█████████▏| 3679/3998 [01:38<00:05, 54.21it/s]

Running loglikelihood requests:  92%|█████████▏| 3688/3998 [01:38<00:05, 53.77it/s]

Running loglikelihood requests:  93%|█████████▎| 3700/3998 [01:38<00:05, 59.41it/s]

Running loglikelihood requests:  93%|█████████▎| 3708/3998 [01:39<00:05, 55.92it/s]

Running loglikelihood requests:  93%|█████████▎| 3720/3998 [01:39<00:04, 61.35it/s]

Running loglikelihood requests:  93%|█████████▎| 3728/3998 [01:39<00:04, 57.58it/s]

Running loglikelihood requests:  93%|█████████▎| 3736/3998 [01:39<00:04, 54.76it/s]

Running loglikelihood requests:  94%|█████████▎| 3747/3998 [01:39<00:04, 59.20it/s]

Running loglikelihood requests:  94%|█████████▍| 3760/3998 [01:39<00:03, 67.93it/s]

Running loglikelihood requests:  94%|█████████▍| 3771/3998 [01:39<00:03, 71.04it/s]

Running loglikelihood requests:  95%|█████████▍| 3781/3998 [01:40<00:03, 71.06it/s]

Running loglikelihood requests:  95%|█████████▍| 3791/3998 [01:40<00:02, 70.96it/s]

Running loglikelihood requests:  95%|█████████▌| 3800/3998 [01:40<00:03, 65.99it/s]

Running loglikelihood requests:  95%|█████████▌| 3808/3998 [01:40<00:03, 61.17it/s]

Running loglikelihood requests:  96%|█████████▌| 3821/3998 [01:40<00:02, 67.47it/s]

Running loglikelihood requests:  96%|█████████▌| 3831/3998 [01:40<00:02, 68.31it/s]

Running loglikelihood requests:  96%|█████████▌| 3841/3998 [01:40<00:02, 68.49it/s]

Running loglikelihood requests:  96%|█████████▋| 3855/3998 [01:41<00:01, 75.73it/s]

Running loglikelihood requests:  97%|█████████▋| 3867/3998 [01:41<00:01, 76.41it/s]

Running loglikelihood requests:  97%|█████████▋| 3882/3998 [01:41<00:01, 82.92it/s]

Running loglikelihood requests:  97%|█████████▋| 3892/3998 [01:41<00:01, 77.27it/s]

Running loglikelihood requests:  98%|█████████▊| 3900/3998 [01:41<00:01, 66.64it/s]

Running loglikelihood requests:  98%|█████████▊| 3912/3998 [01:41<00:01, 70.53it/s]

Running loglikelihood requests:  98%|█████████▊| 3927/3998 [01:42<00:00, 78.11it/s]

Running loglikelihood requests:  99%|█████████▊| 3946/3998 [01:42<00:00, 89.35it/s]

Running loglikelihood requests:  99%|█████████▉| 3955/3998 [01:42<00:00, 77.49it/s]

Running loglikelihood requests:  99%|█████████▉| 3970/3998 [01:42<00:00, 81.57it/s]

Running loglikelihood requests: 100%|█████████▉| 3979/3998 [01:42<00:00, 78.50it/s]

Running loglikelihood requests: 100%|█████████▉| 3992/3998 [01:42<00:00, 88.41it/s]

Running loglikelihood requests: 100%|██████████| 3998/3998 [01:42<00:00, 38.88it/s]

                      hellaswag  arc_easy
name                  hellaswag  arc_easy
alias                 hellaswag  arc_easy
sample_len                  500       500
acc,none                  0.506     0.746
acc_stderr,none        0.022381  0.019487
acc_norm,none              0.62     0.736
acc_norm_stderr,none   0.021729  0.019733

### A.2 · MMLU machine_learning (5-shot y 0-shot)

MMLU completo son 57 dominios. Usamos solo el subset `machine_learning` para que dure razonablemente en clase.

**¿Por que 5-shot y 0-shot?**
- **5-shot** · el setting "oficial" de MMLU. El modelo ve 5 ejemplos antes de cada pregunta.
- **0-shot** · sin ejemplos. Segun la hipotesis clasica, el base sufre aqui porque no sabe "seguir instrucciones".

La diferencia entre ambos te dice cuanto depende de few-shot para responder.

In [ ]:
results_base_mmlu_5shot = eval_mmlu(model_base, num_fewshot=5)
pd.DataFrame(results_base_mmlu_5shot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

README.md:   0%|          | 0.00/53.2k [00:00<?, ?B/s]

dataset_infos.json:   0%|          | 0.00/138k [00:00<?, ?B/s]

machine_learning/test-00000-of-00001.par(…): reconstructing file:   0%|          |  0.00B / 19.7kB

machine_learning/test-00000-of-00001.par(…): downloading bytes:           |  0.00B

machine_learning/validation-00000-of-000(…): reconstructing file:   0%|          |  0.00B / 6.17kB

machine_learning/validation-00000-of-000(…): downloading bytes:           |  0.00B

machine_learning/dev-00000-of-00001.parq(…): reconstructing file:   0%|          |  0.00B / 5.25kB

machine_learning/dev-00000-of-00001.parq(…): downloading bytes:           |  0.00B

Generating test split:   0%|          | 0/112 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/11 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/5 [00:00<?, ? examples/s]

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of mmlu_flan_n_shot_loglikelihood_machine_learning from None to 5

  0%|          | 0/112 [00:00<?, ?it/s]

 11%|█         | 12/112 [00:00<00:00, 114.34it/s]

 21%|██▏       | 24/112 [00:00<00:00, 111.20it/s]

 32%|███▏      | 36/112 [00:00<00:00, 108.33it/s]

 43%|████▎     | 48/112 [00:00<00:00, 109.82it/s]

 54%|█████▎    | 60/112 [00:00<00:00, 111.52it/s]

 64%|██████▍   | 72/112 [00:00<00:00, 109.98it/s]

 76%|███████▌  | 85/112 [00:00<00:00, 115.26it/s]

 87%|████████▋ | 97/112 [00:00<00:00, 116.54it/s]

 98%|█████████▊| 110/112 [00:00<00:00, 119.99it/s]

100%|██████████| 112/112 [00:00<00:00, 114.86it/s]

Tokenizing inputs:   0%|          | 0/448 [00:00<?, ?it/s]

Tokenizing inputs:   8%|▊         | 35/448 [00:00<00:01, 349.74it/s]

Tokenizing inputs:  16%|█▌        | 70/448 [00:00<00:01, 243.04it/s]

Tokenizing inputs:  22%|██▏       | 97/448 [00:00<00:01, 220.54it/s]

Tokenizing inputs:  27%|██▋       | 121/448 [00:00<00:01, 215.82it/s]

Tokenizing inputs:  32%|███▏      | 144/448 [00:00<00:01, 207.75it/s]

Tokenizing inputs:  37%|███▋      | 166/448 [00:00<00:01, 205.30it/s]

Tokenizing inputs:  42%|████▏     | 187/448 [00:00<00:01, 203.27it/s]

Tokenizing inputs:  46%|████▋     | 208/448 [00:00<00:01, 203.23it/s]

Tokenizing inputs:  51%|█████     | 229/448 [00:01<00:01, 202.72it/s]

Tokenizing inputs:  56%|█████▌    | 250/448 [00:01<00:00, 199.25it/s]

Tokenizing inputs:  60%|██████    | 270/448 [00:01<00:00, 195.80it/s]

Tokenizing inputs:  65%|██████▍   | 290/448 [00:01<00:00, 193.40it/s]

Tokenizing inputs:  69%|██████▉   | 310/448 [00:01<00:00, 194.44it/s]

Tokenizing inputs:  74%|███████▎  | 330/448 [00:01<00:00, 193.50it/s]

Tokenizing inputs:  78%|███████▊  | 350/448 [00:01<00:00, 190.72it/s]

Tokenizing inputs:  83%|████████▎ | 371/448 [00:01<00:00, 194.95it/s]

Tokenizing inputs:  87%|████████▋ | 391/448 [00:01<00:00, 195.00it/s]

Tokenizing inputs:  92%|█████████▏| 411/448 [00:02<00:00, 196.29it/s]

Tokenizing inputs:  96%|█████████▌| 431/448 [00:02<00:00, 190.10it/s]

Tokenizing inputs: 100%|██████████| 448/448 [00:02<00:00, 201.65it/s]

Running loglikelihood requests:   0%|          | 0/448 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/448 [00:05<42:19,  5.68s/it]

Running loglikelihood requests:   2%|▏         | 9/448 [00:11<07:53,  1.08s/it]

Running loglikelihood requests:   4%|▍         | 17/448 [00:15<05:46,  1.25it/s]

Running loglikelihood requests:   6%|▌         | 25/448 [00:20<05:02,  1.40it/s]

Running loglikelihood requests:   7%|▋         | 33/448 [00:25<04:36,  1.50it/s]

Running loglikelihood requests:   9%|▉         | 41/448 [00:30<04:19,  1.57it/s]

Running loglikelihood requests:  11%|█         | 49/448 [00:34<04:09,  1.60it/s]

Running loglikelihood requests:  13%|█▎        | 57/448 [00:39<03:59,  1.63it/s]

Running loglikelihood requests:  15%|█▍        | 65/448 [00:44<03:51,  1.66it/s]

Running loglikelihood requests:  16%|█▋        | 73/448 [00:48<03:43,  1.68it/s]

Running loglikelihood requests:  18%|█▊        | 81/448 [00:53<03:32,  1.73it/s]

Running loglikelihood requests:  20%|█▉        | 89/448 [00:57<03:24,  1.76it/s]

Running loglikelihood requests:  22%|██▏       | 97/448 [01:01<03:16,  1.79it/s]

Running loglikelihood requests:  23%|██▎       | 105/448 [01:06<03:09,  1.81it/s]

Running loglikelihood requests:  25%|██▌       | 113/448 [01:10<03:03,  1.83it/s]

Running loglikelihood requests:  27%|██▋       | 121/448 [01:14<02:57,  1.84it/s]

Running loglikelihood requests:  29%|██▉       | 129/448 [01:18<02:51,  1.86it/s]

Running loglikelihood requests:  31%|███       | 137/448 [01:23<02:46,  1.86it/s]

Running loglikelihood requests:  32%|███▏      | 145/448 [01:27<02:41,  1.87it/s]

Running loglikelihood requests:  34%|███▍      | 153/448 [01:31<02:37,  1.87it/s]

Running loglikelihood requests:  36%|███▌      | 161/448 [01:36<02:33,  1.86it/s]

Running loglikelihood requests:  38%|███▊      | 169/448 [01:40<02:29,  1.87it/s]

Running loglikelihood requests:  40%|███▉      | 177/448 [01:44<02:25,  1.86it/s]

Running loglikelihood requests:  41%|████▏     | 185/448 [01:48<02:21,  1.86it/s]

Running loglikelihood requests:  43%|████▎     | 193/448 [01:53<02:17,  1.86it/s]

Running loglikelihood requests:  45%|████▍     | 201/448 [01:57<02:13,  1.86it/s]

Running loglikelihood requests:  47%|████▋     | 209/448 [02:01<02:08,  1.86it/s]

Running loglikelihood requests:  48%|████▊     | 217/448 [02:06<02:03,  1.87it/s]

Running loglikelihood requests:  50%|█████     | 225/448 [02:10<01:59,  1.87it/s]

Running loglikelihood requests:  52%|█████▏    | 233/448 [02:14<01:54,  1.87it/s]

Running loglikelihood requests:  54%|█████▍    | 241/448 [02:18<01:50,  1.88it/s]

Running loglikelihood requests:  56%|█████▌    | 249/448 [02:23<01:45,  1.89it/s]

Running loglikelihood requests:  57%|█████▋    | 257/448 [02:27<01:41,  1.89it/s]

Running loglikelihood requests:  59%|█████▉    | 265/448 [02:31<01:36,  1.90it/s]

Running loglikelihood requests:  61%|██████    | 273/448 [02:35<01:31,  1.90it/s]

Running loglikelihood requests:  63%|██████▎   | 281/448 [02:39<01:27,  1.91it/s]

Running loglikelihood requests:  65%|██████▍   | 289/448 [02:43<01:22,  1.93it/s]

Running loglikelihood requests:  66%|██████▋   | 297/448 [02:47<01:17,  1.95it/s]

Running loglikelihood requests:  68%|██████▊   | 305/448 [02:51<01:13,  1.95it/s]

Running loglikelihood requests:  70%|██████▉   | 313/448 [02:56<01:09,  1.95it/s]

Running loglikelihood requests:  72%|███████▏  | 321/448 [03:00<01:05,  1.95it/s]

Running loglikelihood requests:  73%|███████▎  | 329/448 [03:04<01:00,  1.96it/s]

Running loglikelihood requests:  75%|███████▌  | 337/448 [03:08<00:56,  1.96it/s]

Running loglikelihood requests:  77%|███████▋  | 345/448 [03:12<00:52,  1.96it/s]

Running loglikelihood requests:  79%|███████▉  | 353/448 [03:16<00:48,  1.96it/s]

Running loglikelihood requests:  81%|████████  | 361/448 [03:20<00:44,  1.97it/s]

Running loglikelihood requests:  82%|████████▏ | 369/448 [03:24<00:40,  1.97it/s]

Running loglikelihood requests:  84%|████████▍ | 377/448 [03:28<00:35,  1.98it/s]

Running loglikelihood requests:  86%|████████▌ | 385/448 [03:32<00:31,  1.98it/s]

Running loglikelihood requests:  88%|████████▊ | 393/448 [03:36<00:27,  1.99it/s]

Running loglikelihood requests:  90%|████████▉ | 401/448 [03:40<00:23,  1.99it/s]

Running loglikelihood requests:  91%|█████████▏| 409/448 [03:44<00:19,  2.00it/s]

Running loglikelihood requests:  93%|█████████▎| 417/448 [03:48<00:15,  2.00it/s]

Running loglikelihood requests:  95%|█████████▍| 425/448 [03:52<00:11,  2.00it/s]

Running loglikelihood requests:  97%|█████████▋| 433/448 [03:56<00:07,  2.00it/s]

Running loglikelihood requests:  98%|█████████▊| 441/448 [04:00<00:03,  2.01it/s]

Running loglikelihood requests: 100%|██████████| 448/448 [04:00<00:00,  1.86it/s]

                 mmlu_flan_n_shot_loglikelihood_machine_learning
name             mmlu_flan_n_shot_loglikelihood_machine_learning
alias            mmlu_flan_n_shot_loglikelihood_machine_learning
sample_len                                                   112
acc,none                                                0.651786
acc_stderr,none                                         0.045218

In [ ]:
results_base_mmlu_0shot = eval_mmlu(model_base, num_fewshot=0)
pd.DataFrame(results_base_mmlu_0shot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of mmlu_flan_n_shot_loglikelihood_machine_learning from None to 0

  0%|          | 0/112 [00:00<?, ?it/s]

 56%|█████▋    | 63/112 [00:00<00:00, 619.76it/s]

100%|██████████| 112/112 [00:00<00:00, 612.89it/s]

Tokenizing inputs:   0%|          | 0/448 [00:00<?, ?it/s]

Tokenizing inputs:  45%|████▍     | 200/448 [00:00<00:00, 1998.28it/s]

Tokenizing inputs:  90%|█████████ | 405/448 [00:00<00:00, 2027.57it/s]

Tokenizing inputs: 100%|██████████| 448/448 [00:00<00:00, 1920.24it/s]

Running loglikelihood requests:   0%|          | 0/448 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/448 [00:01<11:13,  1.51s/it]

Running loglikelihood requests:   2%|▏         | 9/448 [00:02<01:52,  3.91it/s]

Running loglikelihood requests:   4%|▍         | 17/448 [00:03<01:16,  5.66it/s]

Running loglikelihood requests:   6%|▌         | 25/448 [00:04<01:02,  6.73it/s]

Running loglikelihood requests:   7%|▋         | 33/448 [00:05<00:53,  7.81it/s]

Running loglikelihood requests:   9%|▉         | 41/448 [00:06<00:47,  8.65it/s]

Running loglikelihood requests:  11%|█         | 49/448 [00:06<00:40,  9.77it/s]

Running loglikelihood requests:  13%|█▎        | 57/448 [00:07<00:36, 10.69it/s]

Running loglikelihood requests:  15%|█▍        | 65/448 [00:07<00:33, 11.39it/s]

Running loglikelihood requests:  16%|█▋        | 73/448 [00:08<00:31, 11.94it/s]

Running loglikelihood requests:  18%|█▊        | 81/448 [00:09<00:29, 12.42it/s]

Running loglikelihood requests:  20%|█▉        | 89/448 [00:09<00:28, 12.79it/s]

Running loglikelihood requests:  22%|██▏       | 97/448 [00:10<00:26, 13.08it/s]

Running loglikelihood requests:  23%|██▎       | 105/448 [00:10<00:25, 13.29it/s]

Running loglikelihood requests:  25%|██▌       | 113/448 [00:11<00:24, 13.45it/s]

Running loglikelihood requests:  27%|██▋       | 121/448 [00:11<00:23, 13.64it/s]

Running loglikelihood requests:  29%|██▉       | 129/448 [00:12<00:23, 13.76it/s]

Running loglikelihood requests:  31%|███       | 137/448 [00:13<00:22, 13.90it/s]

Running loglikelihood requests:  32%|███▏      | 145/448 [00:13<00:21, 14.02it/s]

Running loglikelihood requests:  34%|███▍      | 153/448 [00:14<00:20, 14.06it/s]

Running loglikelihood requests:  36%|███▌      | 161/448 [00:14<00:20, 14.11it/s]

Running loglikelihood requests:  38%|███▊      | 169/448 [00:15<00:19, 14.40it/s]

Running loglikelihood requests:  40%|███▉      | 177/448 [00:15<00:18, 14.61it/s]

Running loglikelihood requests:  41%|████▏     | 185/448 [00:16<00:17, 14.78it/s]

Running loglikelihood requests:  43%|████▎     | 193/448 [00:16<00:17, 14.99it/s]

Running loglikelihood requests:  45%|████▍     | 201/448 [00:17<00:16, 15.12it/s]

Running loglikelihood requests:  47%|████▋     | 209/448 [00:17<00:15, 15.20it/s]

Running loglikelihood requests:  48%|████▊     | 217/448 [00:18<00:15, 15.30it/s]

Running loglikelihood requests:  50%|█████     | 225/448 [00:18<00:14, 15.41it/s]

Running loglikelihood requests:  52%|█████▏    | 233/448 [00:19<00:13, 15.56it/s]

Running loglikelihood requests:  54%|█████▍    | 241/448 [00:19<00:13, 15.63it/s]

Running loglikelihood requests:  56%|█████▌    | 249/448 [00:20<00:12, 15.68it/s]

Running loglikelihood requests:  57%|█████▋    | 257/448 [00:20<00:12, 15.77it/s]

Running loglikelihood requests:  59%|█████▉    | 265/448 [00:21<00:11, 15.83it/s]

Running loglikelihood requests:  61%|██████    | 273/448 [00:21<00:11, 15.88it/s]

Running loglikelihood requests:  63%|██████▎   | 281/448 [00:22<00:10, 15.87it/s]

Running loglikelihood requests:  65%|██████▍   | 289/448 [00:22<00:09, 16.43it/s]

Running loglikelihood requests:  66%|██████▋   | 297/448 [00:23<00:09, 16.75it/s]

Running loglikelihood requests:  68%|██████▊   | 305/448 [00:23<00:08, 17.11it/s]

Running loglikelihood requests:  70%|██████▉   | 313/448 [00:24<00:07, 17.41it/s]

Running loglikelihood requests:  72%|███████▏  | 321/448 [00:24<00:07, 17.64it/s]

Running loglikelihood requests:  73%|███████▎  | 329/448 [00:25<00:06, 17.71it/s]

Running loglikelihood requests:  75%|███████▌  | 337/448 [00:25<00:06, 17.80it/s]

Running loglikelihood requests:  77%|███████▋  | 345/448 [00:25<00:05, 17.93it/s]

Running loglikelihood requests:  79%|███████▉  | 353/448 [00:26<00:05, 18.05it/s]

Running loglikelihood requests:  81%|████████  | 361/448 [00:26<00:04, 18.36it/s]

Running loglikelihood requests:  82%|████████▏ | 369/448 [00:27<00:04, 18.75it/s]

Running loglikelihood requests:  84%|████████▍ | 377/448 [00:27<00:03, 19.10it/s]

Running loglikelihood requests:  86%|████████▌ | 385/448 [00:27<00:03, 20.13it/s]

Running loglikelihood requests:  88%|████████▊ | 393/448 [00:28<00:02, 21.02it/s]

Running loglikelihood requests:  90%|████████▉ | 401/448 [00:28<00:02, 21.72it/s]

Running loglikelihood requests:  91%|█████████▏| 409/448 [00:29<00:01, 22.18it/s]

Running loglikelihood requests:  93%|█████████▎| 417/448 [00:29<00:01, 22.69it/s]

Running loglikelihood requests:  95%|█████████▍| 425/448 [00:29<00:00, 23.37it/s]

Running loglikelihood requests:  97%|█████████▋| 433/448 [00:29<00:00, 23.82it/s]

Running loglikelihood requests:  98%|█████████▊| 441/448 [00:30<00:00, 24.39it/s]

Running loglikelihood requests: 100%|██████████| 448/448 [00:30<00:00, 14.78it/s]

                 mmlu_flan_n_shot_loglikelihood_machine_learning
name             mmlu_flan_n_shot_loglikelihood_machine_learning
alias            mmlu_flan_n_shot_loglikelihood_machine_learning
sample_len                                                   112
acc,none                                                0.535714
acc_stderr,none                                         0.047337

### A.3 · MMLU machine_learning · Chain of Thought (CoT)

CoT pide al modelo que **genere el razonamiento** antes de la respuesta ("Let's think step by step" ... "The answer is (X)"). La hipotesis clasica dice que un base lo hace mal porque no esta entrenado para producir ese texto estructurado.

Dos avisos de protocolo antes de mirar el numero:
- Esta tarea de lm-eval usa el split de validacion de MMLU-ML: **solo 11 preguntas**. Mira el `stderr` (~0,12-0,15): una pregunta arriba o abajo mueve 9 puntos.
- `flexible-extract` busca cualquier "(X)" en la respuesta; `strict-match` exige la frase "The answer is". Comparar las dos te dice si el modelo razona bien pero no respeta el formato.

In [ ]:
results_base_mmlu_cot = eval_mmlu_cot(model_base)
pd.DataFrame(results_base_mmlu_cot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:generation_kwargs: {'max_gen_toks': 384} specified through cli, these settings will update set parameters in yaml tasks. Ensure 'do_sample=True' for non-greedy decoding!

  0%|          | 0/11 [00:00<?, ?it/s]

100%|██████████| 11/11 [00:00<00:00, 408.79it/s]

Running generate_until requests:   0%|          | 0/11 [00:00<?, ?it/s]

Running generate_until requests:   9%|▉         | 1/11 [00:33<05:30, 33.03s/it]

Running generate_until requests:  45%|████▌     | 5/11 [01:05<01:10, 11.74s/it]

Running generate_until requests:  82%|████████▏ | 9/11 [01:37<00:19,  9.79s/it]

Running generate_until requests: 100%|██████████| 11/11 [01:37<00:00,  8.90s/it]

                                     mmlu_flan_cot_zeroshot_machine_learning
name                                 mmlu_flan_cot_zeroshot_machine_learning
alias                                mmlu_flan_cot_zeroshot_machine_learning
sample_len                                                                11
exact_match,strict-match                                            0.181818
exact_match_stderr,strict-match                                     0.121967
exact_match,flexible-extract                                        0.818182
exact_match_stderr,flexible-extract                                 0.121967

### A.4 · Liberar memoria

Antes de cargar el instruct, soltamos el base. Si no, los dos modelos conviven en la GPU (en 4-bit caben en la T4, pero con modelos mayores te quedas sin VRAM). Deberias ver la VRAM volver a ~0 GB.

In [ ]:
del model_base      # borra la referencia global (sin esto la VRAM NO se libera)
free_model()

  VRAM tras liberar: 0.01 GB

---

# Parte B · Modelo INSTRUCT (`MODEL_ID_INSTRUCT`)

`Qwen/Qwen3-4B` es el mismo modelo tras el post-entrenamiento (SFT + RL, con modo de razonamiento "thinking" integrado). La hipotesis clasica espera:

- Mejor en formato A/B/C/D (sabe seguir la instruccion "elige una opcion").
- Mejor en CoT (sabe generar razonamiento estructurado).
- HellaSwag/ARC-Easy parecidos al base (miden conocimiento del mundo; el post-entrenamiento no anade conocimiento).

Ejecutamos los mismos 4 benchmarks, **con el mismo protocolo** (prompts crudos, sin chat template, 4-bit).

In [ ]:
model_instruct, tokenizer_instruct = load_model(MODEL_ID_INSTRUCT)   # MODEL_ID_INSTRUCT viene del selector

Loading Qwen/Qwen3-4B...

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

model.safetensors.index.json:   0%|          | 0.00/32.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

  VRAM: 2.50 GB

In [ ]:
results_instruct_basic = eval_basic(model_instruct)
pd.DataFrame(results_instruct_basic["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of hellaswag from None to 0

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of arc_easy from None to 0

  0%|          | 0/500 [00:00<?, ?it/s]

 25%|██▌       | 126/500 [00:00<00:00, 1257.22it/s]

 50%|█████     | 252/500 [00:00<00:00, 1222.96it/s]

 75%|███████▌  | 375/500 [00:00<00:00, 1218.75it/s]

 99%|█████████▉| 497/500 [00:00<00:00, 1216.59it/s]

100%|██████████| 500/500 [00:00<00:00, 1218.74it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

 10%|█         | 50/500 [00:00<00:00, 491.14it/s]

 20%|██        | 100/500 [00:00<00:00, 481.75it/s]

 30%|██▉       | 149/500 [00:00<00:00, 465.57it/s]

 39%|███▉      | 197/500 [00:00<00:00, 468.95it/s]

 49%|████▉     | 244/500 [00:00<00:00, 455.08it/s]

 58%|█████▊    | 291/500 [00:00<00:00, 458.84it/s]

 68%|██████▊   | 338/500 [00:00<00:00, 461.58it/s]

 77%|███████▋  | 387/500 [00:00<00:00, 467.46it/s]

 87%|████████▋ | 436/500 [00:00<00:00, 473.40it/s]

 97%|█████████▋| 484/500 [00:01<00:00, 470.47it/s]

100%|██████████| 500/500 [00:01<00:00, 465.54it/s]

Tokenizing inputs:   0%|          | 0/3998 [00:00<?, ?it/s]

Tokenizing inputs:  10%|▉         | 381/3998 [00:00<00:00, 3804.15it/s]

Tokenizing inputs:  19%|█▉        | 762/3998 [00:00<00:00, 3669.64it/s]

Tokenizing inputs:  29%|██▊       | 1146/3998 [00:00<00:00, 3741.69it/s]

Tokenizing inputs:  39%|███▊      | 1546/3998 [00:00<00:00, 3840.65it/s]

Tokenizing inputs:  48%|████▊     | 1931/3998 [00:00<00:00, 3731.41it/s]

Tokenizing inputs:  59%|█████▉    | 2363/3998 [00:00<00:00, 3926.25it/s]

Tokenizing inputs:  69%|██████▉   | 2762/3998 [00:00<00:00, 3943.41it/s]

Tokenizing inputs:  80%|████████  | 3213/3998 [00:00<00:00, 4119.73it/s]

Tokenizing inputs:  91%|█████████▏| 3657/3998 [00:00<00:00, 4215.78it/s]

Tokenizing inputs: 100%|██████████| 3998/3998 [00:00<00:00, 4019.20it/s]

Running loglikelihood requests:   0%|          | 0/3998 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/3998 [00:00<1:03:08,  1.06it/s]

Running loglikelihood requests:   0%|          | 9/3998 [00:01<09:13,  7.20it/s]

Running loglikelihood requests:   0%|          | 17/3998 [00:01<06:22, 10.41it/s]

Running loglikelihood requests:   1%|          | 26/3998 [00:02<05:01, 13.17it/s]

Running loglikelihood requests:   1%|          | 34/3998 [00:02<04:37, 14.31it/s]

Running loglikelihood requests:   1%|          | 42/3998 [00:03<04:13, 15.59it/s]

Running loglikelihood requests:   1%|▏         | 50/3998 [00:03<03:57, 16.61it/s]

Running loglikelihood requests:   1%|▏         | 58/3998 [00:04<03:46, 17.36it/s]

Running loglikelihood requests:   2%|▏         | 66/3998 [00:04<03:39, 17.94it/s]

Running loglikelihood requests:   2%|▏         | 74/3998 [00:05<03:34, 18.31it/s]

Running loglikelihood requests:   2%|▏         | 82/3998 [00:05<03:28, 18.79it/s]

Running loglikelihood requests:   2%|▏         | 90/3998 [00:05<03:26, 18.96it/s]

Running loglikelihood requests:   2%|▏         | 98/3998 [00:06<03:24, 19.08it/s]

Running loglikelihood requests:   3%|▎         | 106/3998 [00:06<03:22, 19.22it/s]

Running loglikelihood requests:   3%|▎         | 114/3998 [00:07<03:20, 19.36it/s]

Running loglikelihood requests:   3%|▎         | 122/3998 [00:07<03:18, 19.51it/s]

Running loglikelihood requests:   3%|▎         | 130/3998 [00:07<03:17, 19.63it/s]

Running loglikelihood requests:   3%|▎         | 138/3998 [00:08<03:15, 19.69it/s]

Running loglikelihood requests:   4%|▎         | 146/3998 [00:08<03:14, 19.75it/s]

Running loglikelihood requests:   4%|▍         | 154/3998 [00:09<03:14, 19.73it/s]

Running loglikelihood requests:   4%|▍         | 162/3998 [00:09<03:13, 19.81it/s]

Running loglikelihood requests:   4%|▍         | 170/3998 [00:09<03:12, 19.87it/s]

Running loglikelihood requests:   4%|▍         | 178/3998 [00:10<03:04, 20.66it/s]

Running loglikelihood requests:   5%|▍         | 186/3998 [00:10<02:59, 21.21it/s]

Running loglikelihood requests:   5%|▍         | 194/3998 [00:10<02:55, 21.67it/s]

Running loglikelihood requests:   5%|▌         | 202/3998 [00:11<02:52, 22.00it/s]

Running loglikelihood requests:   5%|▌         | 210/3998 [00:11<02:49, 22.29it/s]

Running loglikelihood requests:   5%|▌         | 218/3998 [00:12<02:48, 22.48it/s]

Running loglikelihood requests:   6%|▌         | 226/3998 [00:12<02:47, 22.55it/s]

Running loglikelihood requests:   6%|▌         | 234/3998 [00:12<02:45, 22.70it/s]

Running loglikelihood requests:   6%|▌         | 242/3998 [00:13<02:44, 22.90it/s]

Running loglikelihood requests:   6%|▋         | 250/3998 [00:13<02:42, 23.07it/s]

Running loglikelihood requests:   6%|▋         | 258/3998 [00:13<02:41, 23.11it/s]

Running loglikelihood requests:   7%|▋         | 266/3998 [00:14<02:40, 23.20it/s]

Running loglikelihood requests:   7%|▋         | 274/3998 [00:14<02:40, 23.26it/s]

Running loglikelihood requests:   7%|▋         | 283/3998 [00:14<02:34, 24.10it/s]

Running loglikelihood requests:   7%|▋         | 291/3998 [00:15<02:35, 23.83it/s]

Running loglikelihood requests:   7%|▋         | 299/3998 [00:15<02:35, 23.75it/s]

Running loglikelihood requests:   8%|▊         | 307/3998 [00:15<02:36, 23.52it/s]

Running loglikelihood requests:   8%|▊         | 315/3998 [00:16<02:37, 23.40it/s]

Running loglikelihood requests:   8%|▊         | 323/3998 [00:16<02:37, 23.38it/s]

Running loglikelihood requests:   8%|▊         | 331/3998 [00:16<02:36, 23.40it/s]

Running loglikelihood requests:   8%|▊         | 339/3998 [00:17<02:36, 23.43it/s]

Running loglikelihood requests:   9%|▊         | 347/3998 [00:17<02:36, 23.30it/s]

Running loglikelihood requests:   9%|▉         | 355/3998 [00:17<02:35, 23.38it/s]

Running loglikelihood requests:   9%|▉         | 363/3998 [00:18<02:36, 23.24it/s]

Running loglikelihood requests:   9%|▉         | 371/3998 [00:18<02:35, 23.28it/s]

Running loglikelihood requests:   9%|▉         | 379/3998 [00:18<02:35, 23.31it/s]

Running loglikelihood requests:  10%|▉         | 387/3998 [00:19<02:34, 23.33it/s]

Running loglikelihood requests:  10%|▉         | 395/3998 [00:19<02:33, 23.42it/s]

Running loglikelihood requests:  10%|█         | 403/3998 [00:19<02:33, 23.48it/s]

Running loglikelihood requests:  10%|█         | 414/3998 [00:20<02:17, 26.09it/s]

Running loglikelihood requests:  11%|█         | 422/3998 [00:20<02:21, 25.23it/s]

Running loglikelihood requests:  11%|█         | 430/3998 [00:20<02:24, 24.69it/s]

Running loglikelihood requests:  11%|█         | 438/3998 [00:21<02:26, 24.29it/s]

Running loglikelihood requests:  11%|█         | 446/3998 [00:21<02:27, 24.01it/s]

Running loglikelihood requests:  11%|█▏        | 456/3998 [00:21<02:19, 25.48it/s]

Running loglikelihood requests:  12%|█▏        | 464/3998 [00:22<02:22, 24.82it/s]

Running loglikelihood requests:  12%|█▏        | 472/3998 [00:22<02:24, 24.34it/s]

Running loglikelihood requests:  12%|█▏        | 480/3998 [00:23<02:26, 24.09it/s]

Running loglikelihood requests:  12%|█▏        | 488/3998 [00:23<02:26, 23.89it/s]

Running loglikelihood requests:  12%|█▏        | 496/3998 [00:23<02:27, 23.74it/s]

Running loglikelihood requests:  13%|█▎        | 506/3998 [00:24<02:17, 25.43it/s]

Running loglikelihood requests:  13%|█▎        | 514/3998 [00:24<02:19, 24.96it/s]

Running loglikelihood requests:  13%|█▎        | 522/3998 [00:24<02:21, 24.58it/s]

Running loglikelihood requests:  13%|█▎        | 530/3998 [00:25<02:22, 24.31it/s]

Running loglikelihood requests:  13%|█▎        | 538/3998 [00:25<02:22, 24.31it/s]

Running loglikelihood requests:  14%|█▎        | 549/3998 [00:25<02:08, 26.76it/s]

Running loglikelihood requests:  14%|█▍        | 557/3998 [00:26<02:12, 25.97it/s]

Running loglikelihood requests:  14%|█▍        | 565/3998 [00:26<02:15, 25.38it/s]

Running loglikelihood requests:  14%|█▍        | 573/3998 [00:26<02:16, 25.11it/s]

Running loglikelihood requests:  15%|█▍        | 581/3998 [00:27<02:18, 24.75it/s]

Running loglikelihood requests:  15%|█▍        | 589/3998 [00:27<02:17, 24.73it/s]

Running loglikelihood requests:  15%|█▌        | 600/3998 [00:27<02:03, 27.48it/s]

Running loglikelihood requests:  15%|█▌        | 608/3998 [00:28<02:07, 26.53it/s]

Running loglikelihood requests:  15%|█▌        | 616/3998 [00:28<02:10, 25.90it/s]

Running loglikelihood requests:  16%|█▌        | 624/3998 [00:28<02:12, 25.48it/s]

Running loglikelihood requests:  16%|█▌        | 632/3998 [00:28<02:13, 25.27it/s]

Running loglikelihood requests:  16%|█▌        | 643/3998 [00:29<02:00, 27.77it/s]

Running loglikelihood requests:  16%|█▋        | 651/3998 [00:29<02:04, 26.91it/s]

Running loglikelihood requests:  16%|█▋        | 659/3998 [00:29<02:07, 26.17it/s]

Running loglikelihood requests:  17%|█▋        | 667/3998 [00:30<02:08, 25.86it/s]

Running loglikelihood requests:  17%|█▋        | 675/3998 [00:30<02:09, 25.59it/s]

Running loglikelihood requests:  17%|█▋        | 683/3998 [00:30<02:10, 25.47it/s]

Running loglikelihood requests:  17%|█▋        | 691/3998 [00:31<02:10, 25.27it/s]

Running loglikelihood requests:  17%|█▋        | 699/3998 [00:31<02:11, 25.15it/s]

Running loglikelihood requests:  18%|█▊        | 707/3998 [00:31<02:10, 25.27it/s]

Running loglikelihood requests:  18%|█▊        | 715/3998 [00:32<02:10, 25.15it/s]

Running loglikelihood requests:  18%|█▊        | 723/3998 [00:32<02:10, 25.18it/s]

Running loglikelihood requests:  18%|█▊        | 731/3998 [00:32<02:09, 25.14it/s]

Running loglikelihood requests:  18%|█▊        | 739/3998 [00:33<02:08, 25.34it/s]

Running loglikelihood requests:  19%|█▊        | 747/3998 [00:33<02:07, 25.40it/s]

Running loglikelihood requests:  19%|█▉        | 755/3998 [00:33<02:07, 25.34it/s]

Running loglikelihood requests:  19%|█▉        | 763/3998 [00:34<02:07, 25.41it/s]

Running loglikelihood requests:  19%|█▉        | 771/3998 [00:34<02:06, 25.59it/s]

Running loglikelihood requests:  19%|█▉        | 779/3998 [00:34<02:03, 26.11it/s]

Running loglikelihood requests:  20%|█▉        | 787/3998 [00:34<02:01, 26.54it/s]

Running loglikelihood requests:  20%|█▉        | 796/3998 [00:35<01:54, 27.99it/s]

Running loglikelihood requests:  20%|██        | 804/3998 [00:35<01:54, 27.79it/s]

Running loglikelihood requests:  20%|██        | 812/3998 [00:35<01:56, 27.46it/s]

Running loglikelihood requests:  21%|██        | 820/3998 [00:36<01:56, 27.38it/s]

Running loglikelihood requests:  21%|██        | 828/3998 [00:36<01:55, 27.53it/s]

Running loglikelihood requests:  21%|██        | 836/3998 [00:36<01:54, 27.66it/s]

Running loglikelihood requests:  21%|██        | 844/3998 [00:37<01:54, 27.44it/s]

Running loglikelihood requests:  21%|██▏       | 852/3998 [00:37<01:53, 27.67it/s]

Running loglikelihood requests:  22%|██▏       | 860/3998 [00:37<01:52, 27.87it/s]

Running loglikelihood requests:  22%|██▏       | 868/3998 [00:37<01:52, 27.76it/s]

Running loglikelihood requests:  22%|██▏       | 876/3998 [00:38<01:53, 27.57it/s]

Running loglikelihood requests:  22%|██▏       | 884/3998 [00:38<01:53, 27.54it/s]

Running loglikelihood requests:  22%|██▏       | 892/3998 [00:38<01:51, 27.78it/s]

Running loglikelihood requests:  23%|██▎       | 900/3998 [00:39<01:51, 27.85it/s]

Running loglikelihood requests:  23%|██▎       | 908/3998 [00:39<01:50, 27.94it/s]

Running loglikelihood requests:  23%|██▎       | 916/3998 [00:39<01:51, 27.68it/s]

Running loglikelihood requests:  23%|██▎       | 924/3998 [00:39<01:49, 28.01it/s]

Running loglikelihood requests:  23%|██▎       | 932/3998 [00:40<01:49, 28.12it/s]

Running loglikelihood requests:  24%|██▎       | 940/3998 [00:40<01:48, 28.25it/s]

Running loglikelihood requests:  24%|██▎       | 948/3998 [00:40<01:47, 28.33it/s]

Running loglikelihood requests:  24%|██▍       | 956/3998 [00:41<01:47, 28.20it/s]

Running loglikelihood requests:  24%|██▍       | 964/3998 [00:41<01:46, 28.44it/s]

Running loglikelihood requests:  24%|██▍       | 972/3998 [00:41<01:45, 28.61it/s]

Running loglikelihood requests:  25%|██▍       | 980/3998 [00:41<01:44, 28.78it/s]

Running loglikelihood requests:  25%|██▍       | 988/3998 [00:42<01:46, 28.17it/s]

Running loglikelihood requests:  25%|██▍       | 996/3998 [00:42<01:45, 28.54it/s]

Running loglikelihood requests:  25%|██▌       | 1004/3998 [00:42<01:44, 28.65it/s]

Running loglikelihood requests:  25%|██▌       | 1012/3998 [00:42<01:44, 28.50it/s]

Running loglikelihood requests:  26%|██▌       | 1020/3998 [00:43<01:44, 28.61it/s]

Running loglikelihood requests:  26%|██▌       | 1028/3998 [00:43<01:43, 28.79it/s]

Running loglikelihood requests:  26%|██▌       | 1036/3998 [00:43<01:42, 28.84it/s]

Running loglikelihood requests:  26%|██▌       | 1044/3998 [00:44<01:41, 29.04it/s]

Running loglikelihood requests:  26%|██▋       | 1053/3998 [00:44<01:37, 30.14it/s]

Running loglikelihood requests:  27%|██▋       | 1061/3998 [00:44<01:38, 29.94it/s]

Running loglikelihood requests:  27%|██▋       | 1069/3998 [00:44<01:38, 29.66it/s]

Running loglikelihood requests:  27%|██▋       | 1077/3998 [00:45<01:38, 29.58it/s]

Running loglikelihood requests:  27%|██▋       | 1085/3998 [00:45<01:38, 29.64it/s]

Running loglikelihood requests:  27%|██▋       | 1093/3998 [00:45<01:38, 29.63it/s]

Running loglikelihood requests:  28%|██▊       | 1101/3998 [00:45<01:38, 29.52it/s]

Running loglikelihood requests:  28%|██▊       | 1109/3998 [00:46<01:36, 29.80it/s]

Running loglikelihood requests:  28%|██▊       | 1117/3998 [00:46<01:36, 29.87it/s]

Running loglikelihood requests:  28%|██▊       | 1128/3998 [00:46<01:26, 33.34it/s]

Running loglikelihood requests:  28%|██▊       | 1136/3998 [00:47<01:28, 32.42it/s]

Running loglikelihood requests:  29%|██▊       | 1144/3998 [00:47<01:30, 31.64it/s]

Running loglikelihood requests:  29%|██▉       | 1152/3998 [00:47<01:31, 31.03it/s]

Running loglikelihood requests:  29%|██▉       | 1160/3998 [00:47<01:32, 30.77it/s]

Running loglikelihood requests:  29%|██▉       | 1168/3998 [00:48<01:32, 30.63it/s]

Running loglikelihood requests:  29%|██▉       | 1176/3998 [00:48<01:32, 30.60it/s]

Running loglikelihood requests:  30%|██▉       | 1184/3998 [00:48<01:32, 30.56it/s]

Running loglikelihood requests:  30%|██▉       | 1192/3998 [00:48<01:31, 30.53it/s]

Running loglikelihood requests:  30%|███       | 1204/3998 [00:49<01:19, 35.06it/s]

Running loglikelihood requests:  30%|███       | 1215/3998 [00:49<01:14, 37.14it/s]

Running loglikelihood requests:  31%|███       | 1223/3998 [00:49<01:18, 35.15it/s]

Running loglikelihood requests:  31%|███       | 1231/3998 [00:49<01:21, 33.76it/s]

Running loglikelihood requests:  31%|███       | 1239/3998 [00:50<01:24, 32.72it/s]

Running loglikelihood requests:  31%|███       | 1247/3998 [00:50<01:25, 32.06it/s]

Running loglikelihood requests:  31%|███▏      | 1255/3998 [00:50<01:26, 31.57it/s]

Running loglikelihood requests:  32%|███▏      | 1263/3998 [00:50<01:27, 31.33it/s]

Running loglikelihood requests:  32%|███▏      | 1271/3998 [00:51<01:27, 31.25it/s]

Running loglikelihood requests:  32%|███▏      | 1279/3998 [00:51<01:27, 31.03it/s]

Running loglikelihood requests:  32%|███▏      | 1287/3998 [00:51<01:27, 30.84it/s]

Running loglikelihood requests:  32%|███▏      | 1295/3998 [00:52<01:27, 30.73it/s]

Running loglikelihood requests:  33%|███▎      | 1303/3998 [00:52<01:27, 30.81it/s]

Running loglikelihood requests:  33%|███▎      | 1311/3998 [00:52<01:27, 30.74it/s]

Running loglikelihood requests:  33%|███▎      | 1319/3998 [00:52<01:27, 30.66it/s]

Running loglikelihood requests:  33%|███▎      | 1327/3998 [00:53<01:27, 30.64it/s]

Running loglikelihood requests:  33%|███▎      | 1335/3998 [00:53<01:26, 30.80it/s]

Running loglikelihood requests:  34%|███▎      | 1343/3998 [00:53<01:25, 30.91it/s]

Running loglikelihood requests:  34%|███▍      | 1351/3998 [00:53<01:25, 30.95it/s]

Running loglikelihood requests:  34%|███▍      | 1359/3998 [00:54<01:25, 30.69it/s]

Running loglikelihood requests:  34%|███▍      | 1367/3998 [00:54<01:25, 30.80it/s]

Running loglikelihood requests:  34%|███▍      | 1375/3998 [00:54<01:25, 30.71it/s]

Running loglikelihood requests:  35%|███▍      | 1383/3998 [00:54<01:25, 30.64it/s]

Running loglikelihood requests:  35%|███▍      | 1393/3998 [00:55<01:19, 32.86it/s]

Running loglikelihood requests:  35%|███▌      | 1401/3998 [00:55<01:20, 32.16it/s]

Running loglikelihood requests:  35%|███▌      | 1411/3998 [00:55<01:16, 33.92it/s]

Running loglikelihood requests:  35%|███▌      | 1419/3998 [00:55<01:18, 32.92it/s]

Running loglikelihood requests:  36%|███▌      | 1427/3998 [00:56<01:19, 32.20it/s]

Running loglikelihood requests:  36%|███▌      | 1435/3998 [00:56<01:20, 31.69it/s]

Running loglikelihood requests:  36%|███▌      | 1443/3998 [00:56<01:21, 31.30it/s]

Running loglikelihood requests:  36%|███▋      | 1451/3998 [00:56<01:21, 31.07it/s]

Running loglikelihood requests:  36%|███▋      | 1459/3998 [00:57<01:22, 30.91it/s]

Running loglikelihood requests:  37%|███▋      | 1467/3998 [00:57<01:22, 30.79it/s]

Running loglikelihood requests:  37%|███▋      | 1475/3998 [00:57<01:21, 30.89it/s]

Running loglikelihood requests:  37%|███▋      | 1483/3998 [00:58<01:21, 31.03it/s]

Running loglikelihood requests:  37%|███▋      | 1491/3998 [00:58<01:20, 31.11it/s]

Running loglikelihood requests:  37%|███▋      | 1499/3998 [00:58<01:20, 30.90it/s]

Running loglikelihood requests:  38%|███▊      | 1511/3998 [00:58<01:10, 35.41it/s]

Running loglikelihood requests:  38%|███▊      | 1519/3998 [00:59<01:12, 34.19it/s]

Running loglikelihood requests:  38%|███▊      | 1527/3998 [00:59<01:14, 33.30it/s]

Running loglikelihood requests:  38%|███▊      | 1535/3998 [00:59<01:15, 32.68it/s]

Running loglikelihood requests:  39%|███▊      | 1543/3998 [00:59<01:16, 32.01it/s]

Running loglikelihood requests:  39%|███▉      | 1551/3998 [01:00<01:17, 31.71it/s]

Running loglikelihood requests:  39%|███▉      | 1559/3998 [01:00<01:17, 31.63it/s]

Running loglikelihood requests:  39%|███▉      | 1567/3998 [01:00<01:17, 31.51it/s]

Running loglikelihood requests:  39%|███▉      | 1575/3998 [01:00<01:17, 31.36it/s]

Running loglikelihood requests:  40%|███▉      | 1583/3998 [01:01<01:16, 31.60it/s]

Running loglikelihood requests:  40%|███▉      | 1591/3998 [01:01<01:16, 31.55it/s]

Running loglikelihood requests:  40%|███▉      | 1599/3998 [01:01<01:15, 31.78it/s]

Running loglikelihood requests:  40%|████      | 1607/3998 [01:01<01:15, 31.76it/s]

Running loglikelihood requests:  40%|████      | 1615/3998 [01:02<01:14, 31.77it/s]

Running loglikelihood requests:  41%|████      | 1623/3998 [01:02<01:14, 31.95it/s]

Running loglikelihood requests:  41%|████      | 1631/3998 [01:02<01:14, 31.71it/s]

Running loglikelihood requests:  41%|████      | 1639/3998 [01:02<01:14, 31.86it/s]

Running loglikelihood requests:  41%|████      | 1647/3998 [01:03<01:13, 31.77it/s]

Running loglikelihood requests:  41%|████▏     | 1655/3998 [01:03<01:13, 31.71it/s]

Running loglikelihood requests:  42%|████▏     | 1663/3998 [01:03<01:13, 31.66it/s]

Running loglikelihood requests:  42%|████▏     | 1671/3998 [01:03<01:13, 31.82it/s]

Running loglikelihood requests:  42%|████▏     | 1679/3998 [01:04<01:12, 32.00it/s]

Running loglikelihood requests:  42%|████▏     | 1687/3998 [01:04<01:12, 31.83it/s]

Running loglikelihood requests:  42%|████▏     | 1695/3998 [01:04<01:11, 32.01it/s]

Running loglikelihood requests:  43%|████▎     | 1705/3998 [01:04<01:06, 34.42it/s]

Running loglikelihood requests:  43%|████▎     | 1713/3998 [01:05<01:08, 33.42it/s]

Running loglikelihood requests:  43%|████▎     | 1721/3998 [01:05<01:09, 32.73it/s]

Running loglikelihood requests:  43%|████▎     | 1731/3998 [01:05<01:04, 34.98it/s]

Running loglikelihood requests:  44%|████▎     | 1740/3998 [01:05<01:03, 35.31it/s]

Running loglikelihood requests:  44%|████▎     | 1748/3998 [01:06<01:05, 34.16it/s]

Running loglikelihood requests:  44%|████▍     | 1756/3998 [01:06<01:07, 33.38it/s]

Running loglikelihood requests:  44%|████▍     | 1764/3998 [01:06<01:08, 32.78it/s]

Running loglikelihood requests:  44%|████▍     | 1772/3998 [01:06<01:08, 32.49it/s]

Running loglikelihood requests:  45%|████▍     | 1780/3998 [01:07<01:08, 32.34it/s]

Running loglikelihood requests:  45%|████▍     | 1788/3998 [01:07<01:08, 32.12it/s]

Running loglikelihood requests:  45%|████▍     | 1796/3998 [01:07<01:09, 31.81it/s]

Running loglikelihood requests:  45%|████▌     | 1804/3998 [01:07<01:08, 31.89it/s]

Running loglikelihood requests:  45%|████▌     | 1812/3998 [01:08<01:08, 31.91it/s]

Running loglikelihood requests:  46%|████▌     | 1820/3998 [01:08<01:08, 31.98it/s]

Running loglikelihood requests:  46%|████▌     | 1831/3998 [01:08<01:00, 35.68it/s]

Running loglikelihood requests:  46%|████▌     | 1842/3998 [01:08<00:56, 38.01it/s]

Running loglikelihood requests:  46%|████▋     | 1850/3998 [01:09<00:59, 36.34it/s]

Running loglikelihood requests:  46%|████▋     | 1858/3998 [01:09<01:00, 35.14it/s]

Running loglikelihood requests:  47%|████▋     | 1867/3998 [01:09<01:00, 35.40it/s]

Running loglikelihood requests:  47%|████▋     | 1875/3998 [01:09<01:01, 34.58it/s]

Running loglikelihood requests:  47%|████▋     | 1883/3998 [01:10<01:02, 33.99it/s]

Running loglikelihood requests:  47%|████▋     | 1891/3998 [01:10<01:02, 33.53it/s]

Running loglikelihood requests:  47%|████▋     | 1899/3998 [01:10<01:03, 32.92it/s]

Running loglikelihood requests:  48%|████▊     | 1907/3998 [01:10<01:03, 32.83it/s]

Running loglikelihood requests:  48%|████▊     | 1915/3998 [01:11<01:03, 32.97it/s]

Running loglikelihood requests:  48%|████▊     | 1923/3998 [01:11<01:02, 32.99it/s]

Running loglikelihood requests:  48%|████▊     | 1931/3998 [01:11<01:02, 32.98it/s]

Running loglikelihood requests:  48%|████▊     | 1939/3998 [01:11<01:02, 32.90it/s]

Running loglikelihood requests:  49%|████▊     | 1947/3998 [01:12<01:02, 32.92it/s]

Running loglikelihood requests:  49%|████▉     | 1957/3998 [01:12<00:57, 35.22it/s]

Running loglikelihood requests:  49%|████▉     | 1965/3998 [01:12<00:58, 34.46it/s]

Running loglikelihood requests:  49%|████▉     | 1973/3998 [01:12<00:59, 33.99it/s]

Running loglikelihood requests:  50%|████▉     | 1981/3998 [01:13<01:00, 33.46it/s]

Running loglikelihood requests:  50%|████▉     | 1989/3998 [01:13<01:00, 32.98it/s]

Running loglikelihood requests:  50%|████▉     | 1997/3998 [01:13<01:00, 32.88it/s]

Running loglikelihood requests:  50%|█████     | 2005/3998 [01:13<01:00, 32.76it/s]

Running loglikelihood requests:  50%|█████     | 2013/3998 [01:14<01:00, 32.61it/s]

Running loglikelihood requests:  51%|█████     | 2021/3998 [01:14<01:00, 32.54it/s]

Running loglikelihood requests:  51%|█████     | 2029/3998 [01:14<01:00, 32.51it/s]

Running loglikelihood requests:  51%|█████     | 2037/3998 [01:14<01:00, 32.57it/s]

Running loglikelihood requests:  51%|█████     | 2045/3998 [01:15<00:59, 32.67it/s]

Running loglikelihood requests:  51%|█████▏    | 2053/3998 [01:15<00:59, 32.71it/s]

Running loglikelihood requests:  52%|█████▏    | 2061/3998 [01:15<00:59, 32.62it/s]

Running loglikelihood requests:  52%|█████▏    | 2069/3998 [01:15<00:59, 32.57it/s]

Running loglikelihood requests:  52%|█████▏    | 2079/3998 [01:16<00:55, 34.81it/s]

Running loglikelihood requests:  52%|█████▏    | 2087/3998 [01:16<00:55, 34.21it/s]

Running loglikelihood requests:  52%|█████▏    | 2095/3998 [01:16<00:56, 33.78it/s]

Running loglikelihood requests:  53%|█████▎    | 2103/3998 [01:16<00:56, 33.43it/s]

Running loglikelihood requests:  53%|█████▎    | 2111/3998 [01:17<00:57, 33.04it/s]

Running loglikelihood requests:  53%|█████▎    | 2119/3998 [01:17<00:57, 32.87it/s]

Running loglikelihood requests:  53%|█████▎    | 2127/3998 [01:17<00:56, 32.89it/s]

Running loglikelihood requests:  53%|█████▎    | 2136/3998 [01:17<00:54, 34.03it/s]

Running loglikelihood requests:  54%|█████▎    | 2144/3998 [01:18<00:55, 33.67it/s]

Running loglikelihood requests:  54%|█████▍    | 2152/3998 [01:18<00:55, 33.48it/s]

Running loglikelihood requests:  54%|█████▍    | 2160/3998 [01:18<00:55, 33.32it/s]

Running loglikelihood requests:  54%|█████▍    | 2171/3998 [01:18<00:49, 36.88it/s]

Running loglikelihood requests:  55%|█████▍    | 2179/3998 [01:18<00:50, 35.67it/s]

Running loglikelihood requests:  55%|█████▍    | 2187/3998 [01:19<00:51, 34.86it/s]

Running loglikelihood requests:  55%|█████▍    | 2195/3998 [01:19<00:52, 34.19it/s]

Running loglikelihood requests:  55%|█████▌    | 2203/3998 [01:19<00:53, 33.68it/s]

Running loglikelihood requests:  55%|█████▌    | 2211/3998 [01:19<00:53, 33.22it/s]

Running loglikelihood requests:  56%|█████▌    | 2219/3998 [01:20<00:51, 34.80it/s]

Running loglikelihood requests:  56%|█████▌    | 2227/3998 [01:20<00:49, 35.89it/s]

Running loglikelihood requests:  56%|█████▌    | 2235/3998 [01:20<00:47, 37.02it/s]

Running loglikelihood requests:  56%|█████▌    | 2243/3998 [01:20<00:46, 37.43it/s]

Running loglikelihood requests:  56%|█████▋    | 2251/3998 [01:21<00:46, 37.51it/s]

Running loglikelihood requests:  57%|█████▋    | 2259/3998 [01:21<00:45, 38.02it/s]

Running loglikelihood requests:  57%|█████▋    | 2268/3998 [01:21<00:43, 39.57it/s]

Running loglikelihood requests:  57%|█████▋    | 2281/3998 [01:21<00:36, 46.64it/s]

Running loglikelihood requests:  57%|█████▋    | 2289/3998 [01:21<00:38, 43.95it/s]

Running loglikelihood requests:  58%|█████▊    | 2300/3998 [01:22<00:36, 46.49it/s]

Running loglikelihood requests:  58%|█████▊    | 2308/3998 [01:22<00:38, 44.17it/s]

Running loglikelihood requests:  58%|█████▊    | 2316/3998 [01:22<00:39, 42.24it/s]

Running loglikelihood requests:  58%|█████▊    | 2324/3998 [01:22<00:40, 41.05it/s]

Running loglikelihood requests:  58%|█████▊    | 2332/3998 [01:22<00:41, 40.36it/s]

Running loglikelihood requests:  59%|█████▊    | 2340/3998 [01:23<00:41, 39.78it/s]

Running loglikelihood requests:  59%|█████▊    | 2348/3998 [01:23<00:41, 39.61it/s]

Running loglikelihood requests:  59%|█████▉    | 2357/3998 [01:23<00:39, 41.06it/s]

Running loglikelihood requests:  59%|█████▉    | 2367/3998 [01:23<00:37, 43.50it/s]

Running loglikelihood requests:  59%|█████▉    | 2375/3998 [01:23<00:38, 42.23it/s]

Running loglikelihood requests:  60%|█████▉    | 2384/3998 [01:24<00:37, 42.67it/s]

Running loglikelihood requests:  60%|█████▉    | 2396/3998 [01:24<00:33, 47.30it/s]

Running loglikelihood requests:  60%|██████    | 2404/3998 [01:24<00:35, 44.39it/s]

Running loglikelihood requests:  60%|██████    | 2412/3998 [01:24<00:37, 42.78it/s]

Running loglikelihood requests:  61%|██████    | 2420/3998 [01:24<00:37, 41.72it/s]

Running loglikelihood requests:  61%|██████    | 2428/3998 [01:25<00:38, 41.00it/s]

Running loglikelihood requests:  61%|██████    | 2439/3998 [01:25<00:34, 44.75it/s]

Running loglikelihood requests:  61%|██████    | 2447/3998 [01:25<00:36, 42.89it/s]

Running loglikelihood requests:  61%|██████▏   | 2455/3998 [01:25<00:37, 41.65it/s]

Running loglikelihood requests:  62%|██████▏   | 2466/3998 [01:25<00:33, 45.08it/s]

Running loglikelihood requests:  62%|██████▏   | 2474/3998 [01:26<00:35, 43.15it/s]

Running loglikelihood requests:  62%|██████▏   | 2482/3998 [01:26<00:36, 41.79it/s]

Running loglikelihood requests:  62%|██████▏   | 2490/3998 [01:26<00:36, 40.87it/s]

Running loglikelihood requests:  62%|██████▏   | 2498/3998 [01:26<00:37, 40.45it/s]

Running loglikelihood requests:  63%|██████▎   | 2506/3998 [01:26<00:37, 40.17it/s]

Running loglikelihood requests:  63%|██████▎   | 2514/3998 [01:27<00:37, 39.84it/s]

Running loglikelihood requests:  63%|██████▎   | 2522/3998 [01:27<00:37, 39.76it/s]

Running loglikelihood requests:  63%|██████▎   | 2530/3998 [01:27<00:36, 39.70it/s]

Running loglikelihood requests:  63%|██████▎   | 2538/3998 [01:27<00:36, 39.56it/s]

Running loglikelihood requests:  64%|██████▎   | 2546/3998 [01:28<00:36, 39.41it/s]

Running loglikelihood requests:  64%|██████▍   | 2556/3998 [01:28<00:34, 42.24it/s]

Running loglikelihood requests:  64%|██████▍   | 2567/3998 [01:28<00:31, 45.78it/s]

Running loglikelihood requests:  64%|██████▍   | 2576/3998 [01:28<00:31, 44.97it/s]

Running loglikelihood requests:  65%|██████▍   | 2584/3998 [01:28<00:32, 43.40it/s]

Running loglikelihood requests:  65%|██████▍   | 2595/3998 [01:29<00:30, 46.66it/s]

Running loglikelihood requests:  65%|██████▌   | 2603/3998 [01:29<00:31, 44.46it/s]

Running loglikelihood requests:  65%|██████▌   | 2612/3998 [01:29<00:31, 44.49it/s]

Running loglikelihood requests:  66%|██████▌   | 2623/3998 [01:29<00:28, 47.42it/s]

Running loglikelihood requests:  66%|██████▌   | 2631/3998 [01:29<00:30, 45.00it/s]

Running loglikelihood requests:  66%|██████▌   | 2639/3998 [01:30<00:31, 43.32it/s]

Running loglikelihood requests:  66%|██████▌   | 2647/3998 [01:30<00:32, 42.02it/s]

Running loglikelihood requests:  66%|██████▋   | 2655/3998 [01:30<00:32, 41.13it/s]

Running loglikelihood requests:  67%|██████▋   | 2664/3998 [01:30<00:31, 41.92it/s]

Running loglikelihood requests:  67%|██████▋   | 2672/3998 [01:30<00:32, 40.87it/s]

Running loglikelihood requests:  67%|██████▋   | 2682/3998 [01:31<00:30, 43.45it/s]

Running loglikelihood requests:  67%|██████▋   | 2690/3998 [01:31<00:30, 42.25it/s]

Running loglikelihood requests:  67%|██████▋   | 2698/3998 [01:31<00:31, 41.50it/s]

Running loglikelihood requests:  68%|██████▊   | 2711/3998 [01:31<00:26, 48.09it/s]

Running loglikelihood requests:  68%|██████▊   | 2719/3998 [01:31<00:28, 45.43it/s]

Running loglikelihood requests:  68%|██████▊   | 2727/3998 [01:32<00:29, 42.89it/s]

Running loglikelihood requests:  68%|██████▊   | 2735/3998 [01:32<00:30, 41.87it/s]

Running loglikelihood requests:  69%|██████▊   | 2743/3998 [01:32<00:30, 41.02it/s]

Running loglikelihood requests:  69%|██████▉   | 2751/3998 [01:32<00:30, 40.82it/s]

Running loglikelihood requests:  69%|██████▉   | 2759/3998 [01:32<00:30, 40.37it/s]

Running loglikelihood requests:  69%|██████▉   | 2767/3998 [01:33<00:30, 40.05it/s]

Running loglikelihood requests:  69%|██████▉   | 2775/3998 [01:33<00:30, 40.08it/s]

Running loglikelihood requests:  70%|██████▉   | 2786/3998 [01:33<00:27, 44.45it/s]

Running loglikelihood requests:  70%|██████▉   | 2794/3998 [01:33<00:27, 43.07it/s]

Running loglikelihood requests:  70%|███████   | 2802/3998 [01:33<00:28, 41.94it/s]

Running loglikelihood requests:  70%|███████   | 2810/3998 [01:34<00:29, 40.91it/s]

Running loglikelihood requests:  70%|███████   | 2818/3998 [01:34<00:28, 40.90it/s]

Running loglikelihood requests:  71%|███████   | 2826/3998 [01:34<00:28, 40.43it/s]

Running loglikelihood requests:  71%|███████   | 2834/3998 [01:34<00:28, 40.30it/s]

Running loglikelihood requests:  71%|███████   | 2842/3998 [01:34<00:28, 40.44it/s]

Running loglikelihood requests:  71%|███████▏  | 2853/3998 [01:35<00:25, 44.41it/s]

Running loglikelihood requests:  72%|███████▏  | 2861/3998 [01:35<00:26, 43.22it/s]

Running loglikelihood requests:  72%|███████▏  | 2869/3998 [01:35<00:26, 42.08it/s]

Running loglikelihood requests:  72%|███████▏  | 2880/3998 [01:35<00:24, 45.72it/s]

Running loglikelihood requests:  72%|███████▏  | 2888/3998 [01:35<00:25, 43.84it/s]

Running loglikelihood requests:  72%|███████▏  | 2896/3998 [01:36<00:25, 42.45it/s]

Running loglikelihood requests:  73%|███████▎  | 2904/3998 [01:36<00:26, 41.56it/s]

Running loglikelihood requests:  73%|███████▎  | 2915/3998 [01:36<00:23, 45.34it/s]

Running loglikelihood requests:  73%|███████▎  | 2923/3998 [01:36<00:24, 43.70it/s]

Running loglikelihood requests:  73%|███████▎  | 2931/3998 [01:36<00:25, 42.43it/s]

Running loglikelihood requests:  74%|███████▎  | 2939/3998 [01:37<00:25, 42.09it/s]

Running loglikelihood requests:  74%|███████▎  | 2947/3998 [01:37<00:25, 41.22it/s]

Running loglikelihood requests:  74%|███████▍  | 2955/3998 [01:37<00:25, 40.75it/s]

Running loglikelihood requests:  74%|███████▍  | 2963/3998 [01:37<00:25, 40.43it/s]

Running loglikelihood requests:  74%|███████▍  | 2971/3998 [01:37<00:25, 40.13it/s]

Running loglikelihood requests:  75%|███████▍  | 2979/3998 [01:38<00:25, 39.88it/s]

Running loglikelihood requests:  75%|███████▍  | 2987/3998 [01:38<00:25, 39.64it/s]

Running loglikelihood requests:  75%|███████▍  | 2995/3998 [01:38<00:25, 39.64it/s]

Running loglikelihood requests:  75%|███████▌  | 3006/3998 [01:38<00:22, 44.01it/s]

Running loglikelihood requests:  75%|███████▌  | 3014/3998 [01:38<00:23, 42.71it/s]

Running loglikelihood requests:  76%|███████▌  | 3022/3998 [01:39<00:23, 42.14it/s]

Running loglikelihood requests:  76%|███████▌  | 3030/3998 [01:39<00:23, 41.42it/s]

Running loglikelihood requests:  76%|███████▌  | 3038/3998 [01:39<00:23, 41.22it/s]

Running loglikelihood requests:  76%|███████▌  | 3046/3998 [01:39<00:22, 41.42it/s]

Running loglikelihood requests:  76%|███████▋  | 3057/3998 [01:39<00:20, 45.57it/s]

Running loglikelihood requests:  77%|███████▋  | 3065/3998 [01:40<00:21, 44.12it/s]

Running loglikelihood requests:  77%|███████▋  | 3075/3998 [01:40<00:19, 46.34it/s]

Running loglikelihood requests:  77%|███████▋  | 3083/3998 [01:40<00:20, 44.67it/s]

Running loglikelihood requests:  77%|███████▋  | 3091/3998 [01:40<00:21, 43.09it/s]

Running loglikelihood requests:  78%|███████▊  | 3099/3998 [01:40<00:21, 42.04it/s]

Running loglikelihood requests:  78%|███████▊  | 3107/3998 [01:41<00:21, 41.27it/s]

Running loglikelihood requests:  78%|███████▊  | 3115/3998 [01:41<00:21, 40.74it/s]

Running loglikelihood requests:  78%|███████▊  | 3123/3998 [01:41<00:21, 40.68it/s]

Running loglikelihood requests:  78%|███████▊  | 3131/3998 [01:41<00:21, 40.88it/s]

Running loglikelihood requests:  79%|███████▊  | 3139/3998 [01:41<00:21, 40.86it/s]

Running loglikelihood requests:  79%|███████▉  | 3151/3998 [01:42<00:18, 46.71it/s]

Running loglikelihood requests:  79%|███████▉  | 3163/3998 [01:42<00:16, 50.85it/s]

Running loglikelihood requests:  79%|███████▉  | 3177/3998 [01:42<00:14, 57.51it/s]

Running loglikelihood requests:  80%|███████▉  | 3189/3998 [01:42<00:13, 58.40it/s]

Running loglikelihood requests:  80%|███████▉  | 3197/3998 [01:42<00:15, 53.08it/s]

Running loglikelihood requests:  80%|████████  | 3205/3998 [01:43<00:15, 50.00it/s]

Running loglikelihood requests:  80%|████████  | 3218/3998 [01:43<00:14, 54.60it/s]

Running loglikelihood requests:  81%|████████  | 3226/3998 [01:43<00:15, 51.22it/s]

Running loglikelihood requests:  81%|████████  | 3234/3998 [01:43<00:15, 47.81it/s]

Running loglikelihood requests:  81%|████████  | 3242/3998 [01:43<00:16, 46.29it/s]

Running loglikelihood requests:  81%|████████▏ | 3250/3998 [01:44<00:16, 44.66it/s]

Running loglikelihood requests:  81%|████████▏ | 3258/3998 [01:44<00:17, 43.53it/s]

Running loglikelihood requests:  82%|████████▏ | 3266/3998 [01:44<00:16, 43.11it/s]

Running loglikelihood requests:  82%|████████▏ | 3274/3998 [01:44<00:16, 42.88it/s]

Running loglikelihood requests:  82%|████████▏ | 3282/3998 [01:44<00:16, 42.62it/s]

Running loglikelihood requests:  82%|████████▏ | 3290/3998 [01:45<00:16, 42.90it/s]

Running loglikelihood requests:  83%|████████▎ | 3299/3998 [01:45<00:15, 44.44it/s]

Running loglikelihood requests:  83%|████████▎ | 3307/3998 [01:45<00:16, 43.09it/s]

Running loglikelihood requests:  83%|████████▎ | 3315/3998 [01:45<00:15, 42.89it/s]

Running loglikelihood requests:  83%|████████▎ | 3323/3998 [01:45<00:15, 42.67it/s]

Running loglikelihood requests:  83%|████████▎ | 3331/3998 [01:45<00:15, 42.87it/s]

Running loglikelihood requests:  84%|████████▎ | 3342/3998 [01:46<00:13, 47.84it/s]

Running loglikelihood requests:  84%|████████▍ | 3353/3998 [01:46<00:12, 51.42it/s]

Running loglikelihood requests:  84%|████████▍ | 3364/3998 [01:46<00:11, 53.53it/s]

Running loglikelihood requests:  84%|████████▍ | 3373/3998 [01:46<00:12, 51.68it/s]

Running loglikelihood requests:  85%|████████▍ | 3383/3998 [01:46<00:11, 52.28it/s]

Running loglikelihood requests:  85%|████████▍ | 3391/3998 [01:47<00:12, 49.22it/s]

Running loglikelihood requests:  85%|████████▌ | 3401/3998 [01:47<00:11, 50.03it/s]

Running loglikelihood requests:  85%|████████▌ | 3410/3998 [01:47<00:11, 49.46it/s]

Running loglikelihood requests:  86%|████████▌ | 3421/3998 [01:47<00:11, 51.98it/s]

Running loglikelihood requests:  86%|████████▌ | 3432/3998 [01:47<00:10, 54.33it/s]

Running loglikelihood requests:  86%|████████▌ | 3440/3998 [01:48<00:10, 51.61it/s]

Running loglikelihood requests:  86%|████████▋ | 3450/3998 [01:48<00:10, 52.55it/s]

Running loglikelihood requests:  86%|████████▋ | 3458/3998 [01:48<00:10, 50.03it/s]

Running loglikelihood requests:  87%|████████▋ | 3469/3998 [01:48<00:10, 52.87it/s]

Running loglikelihood requests:  87%|████████▋ | 3480/3998 [01:48<00:09, 55.31it/s]

Running loglikelihood requests:  87%|████████▋ | 3488/3998 [01:48<00:09, 52.38it/s]

Running loglikelihood requests:  88%|████████▊ | 3500/3998 [01:49<00:08, 56.02it/s]

Running loglikelihood requests:  88%|████████▊ | 3508/3998 [01:49<00:09, 52.76it/s]

Running loglikelihood requests:  88%|████████▊ | 3516/3998 [01:49<00:09, 49.93it/s]

Running loglikelihood requests:  88%|████████▊ | 3524/3998 [01:49<00:09, 48.19it/s]

Running loglikelihood requests:  88%|████████▊ | 3532/3998 [01:49<00:09, 47.17it/s]

Running loglikelihood requests:  89%|████████▊ | 3540/3998 [01:50<00:09, 46.33it/s]

Running loglikelihood requests:  89%|████████▊ | 3548/3998 [01:50<00:09, 45.63it/s]

Running loglikelihood requests:  89%|████████▉ | 3559/3998 [01:50<00:08, 49.84it/s]

Running loglikelihood requests:  89%|████████▉ | 3567/3998 [01:50<00:08, 48.11it/s]

Running loglikelihood requests:  89%|████████▉ | 3575/3998 [01:50<00:09, 46.96it/s]

Running loglikelihood requests:  90%|████████▉ | 3588/3998 [01:50<00:07, 54.34it/s]

Running loglikelihood requests:  90%|████████▉ | 3596/3998 [01:51<00:07, 51.41it/s]

Running loglikelihood requests:  90%|█████████ | 3604/3998 [01:51<00:07, 49.26it/s]

Running loglikelihood requests:  90%|█████████ | 3613/3998 [01:51<00:07, 49.41it/s]

Running loglikelihood requests:  91%|█████████ | 3621/3998 [01:51<00:07, 47.98it/s]

Running loglikelihood requests:  91%|█████████ | 3631/3998 [01:51<00:07, 50.85it/s]

Running loglikelihood requests:  91%|█████████ | 3642/3998 [01:51<00:06, 54.58it/s]

Running loglikelihood requests:  91%|█████████▏| 3653/3998 [01:52<00:06, 56.72it/s]

Running loglikelihood requests:  92%|█████████▏| 3663/3998 [01:52<00:05, 56.31it/s]

Running loglikelihood requests:  92%|█████████▏| 3671/3998 [01:52<00:06, 53.52it/s]

Running loglikelihood requests:  92%|█████████▏| 3679/3998 [01:52<00:06, 51.32it/s]

Running loglikelihood requests:  92%|█████████▏| 3688/3998 [01:52<00:06, 51.43it/s]

Running loglikelihood requests:  93%|█████████▎| 3700/3998 [01:53<00:05, 56.86it/s]

Running loglikelihood requests:  93%|█████████▎| 3708/3998 [01:53<00:05, 53.59it/s]

Running loglikelihood requests:  93%|█████████▎| 3720/3998 [01:53<00:04, 59.54it/s]

Running loglikelihood requests:  93%|█████████▎| 3728/3998 [01:53<00:04, 56.06it/s]

Running loglikelihood requests:  93%|█████████▎| 3736/3998 [01:53<00:04, 53.42it/s]

Running loglikelihood requests:  94%|█████████▎| 3747/3998 [01:53<00:04, 58.56it/s]

Running loglikelihood requests:  94%|█████████▍| 3760/3998 [01:54<00:03, 67.68it/s]

Running loglikelihood requests:  94%|█████████▍| 3771/3998 [01:54<00:03, 70.37it/s]

Running loglikelihood requests:  95%|█████████▍| 3781/3998 [01:54<00:03, 70.53it/s]

Running loglikelihood requests:  95%|█████████▍| 3791/3998 [01:54<00:03, 66.39it/s]

Running loglikelihood requests:  95%|█████████▌| 3800/3998 [01:54<00:03, 64.26it/s]

Running loglikelihood requests:  95%|█████████▌| 3808/3998 [01:54<00:03, 61.71it/s]

Running loglikelihood requests:  96%|█████████▌| 3821/3998 [01:54<00:02, 68.46it/s]

Running loglikelihood requests:  96%|█████████▌| 3831/3998 [01:55<00:02, 68.41it/s]

Running loglikelihood requests:  96%|█████████▌| 3841/3998 [01:55<00:02, 68.40it/s]

Running loglikelihood requests:  96%|█████████▋| 3855/3998 [01:55<00:01, 76.60it/s]

Running loglikelihood requests:  97%|█████████▋| 3867/3998 [01:55<00:01, 78.80it/s]

Running loglikelihood requests:  97%|█████████▋| 3882/3998 [01:55<00:01, 86.79it/s]

Running loglikelihood requests:  97%|█████████▋| 3892/3998 [01:55<00:01, 79.92it/s]

Running loglikelihood requests:  98%|█████████▊| 3901/3998 [01:55<00:01, 72.73it/s]

Running loglikelihood requests:  98%|█████████▊| 3912/3998 [01:56<00:01, 72.67it/s]

Running loglikelihood requests:  98%|█████████▊| 3927/3998 [01:56<00:00, 76.52it/s]

Running loglikelihood requests:  99%|█████████▊| 3946/3998 [01:56<00:00, 87.44it/s]

Running loglikelihood requests:  99%|█████████▉| 3955/3998 [01:56<00:00, 82.19it/s]

Running loglikelihood requests:  99%|█████████▉| 3970/3998 [01:56<00:00, 89.84it/s]

Running loglikelihood requests: 100%|█████████▉| 3979/3998 [01:56<00:00, 83.53it/s]

Running loglikelihood requests: 100%|█████████▉| 3992/3998 [01:56<00:00, 92.06it/s]

Running loglikelihood requests: 100%|██████████| 3998/3998 [01:56<00:00, 34.18it/s]

                      hellaswag  arc_easy
name                  hellaswag  arc_easy
alias                 hellaswag  arc_easy
sample_len                  500       500
acc,none                  0.476     0.786
acc_stderr,none        0.022357   0.01836
acc_norm,none              0.57     0.766
acc_norm_stderr,none   0.022163  0.018953

In [ ]:
results_instruct_mmlu_5shot = eval_mmlu(model_instruct, num_fewshot=5)
pd.DataFrame(results_instruct_mmlu_5shot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of mmlu_flan_n_shot_loglikelihood_machine_learning from None to 5

  0%|          | 0/112 [00:00<?, ?it/s]

 12%|█▏        | 13/112 [00:00<00:00, 127.46it/s]

 23%|██▎       | 26/112 [00:00<00:00, 127.00it/s]

 36%|███▌      | 40/112 [00:00<00:00, 128.54it/s]

 47%|████▋     | 53/112 [00:00<00:00, 122.94it/s]

 59%|█████▉    | 66/112 [00:00<00:00, 123.10it/s]

 71%|███████   | 79/112 [00:00<00:00, 122.56it/s]

 82%|████████▏ | 92/112 [00:00<00:00, 124.28it/s]

 94%|█████████▍| 105/112 [00:00<00:00, 124.24it/s]

100%|██████████| 112/112 [00:00<00:00, 124.68it/s]

Tokenizing inputs:   0%|          | 0/448 [00:00<?, ?it/s]

Tokenizing inputs:   8%|▊         | 35/448 [00:00<00:01, 348.69it/s]

Tokenizing inputs:  16%|█▌        | 71/448 [00:00<00:01, 350.83it/s]

Tokenizing inputs:  24%|██▍       | 107/448 [00:00<00:00, 347.12it/s]

Tokenizing inputs:  32%|███▏      | 142/448 [00:00<00:00, 344.70it/s]

Tokenizing inputs:  40%|███▉      | 177/448 [00:00<00:00, 331.02it/s]

Tokenizing inputs:  47%|████▋     | 211/448 [00:00<00:00, 327.33it/s]

Tokenizing inputs:  55%|█████▍    | 245/448 [00:00<00:00, 330.36it/s]

Tokenizing inputs:  63%|██████▎   | 281/448 [00:00<00:00, 336.74it/s]

Tokenizing inputs:  70%|███████   | 315/448 [00:00<00:00, 334.82it/s]

Tokenizing inputs:  78%|███████▊  | 349/448 [00:01<00:00, 336.02it/s]

Tokenizing inputs:  86%|████████▌ | 384/448 [00:01<00:00, 339.34it/s]

Tokenizing inputs:  93%|█████████▎| 418/448 [00:01<00:00, 339.43it/s]

Tokenizing inputs: 100%|██████████| 448/448 [00:01<00:00, 336.47it/s]

Running loglikelihood requests:   0%|          | 0/448 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/448 [00:05<42:41,  5.73s/it]

Running loglikelihood requests:   2%|▏         | 9/448 [00:11<07:56,  1.08s/it]

Running loglikelihood requests:   4%|▍         | 17/448 [00:15<05:47,  1.24it/s]

Running loglikelihood requests:   6%|▌         | 25/448 [00:20<05:04,  1.39it/s]

Running loglikelihood requests:   7%|▋         | 33/448 [00:25<04:39,  1.48it/s]

Running loglikelihood requests:   9%|▉         | 41/448 [00:30<04:22,  1.55it/s]

Running loglikelihood requests:  11%|█         | 49/448 [00:35<04:09,  1.60it/s]

Running loglikelihood requests:  13%|█▎        | 57/448 [00:39<03:59,  1.63it/s]

Running loglikelihood requests:  15%|█▍        | 65/448 [00:44<03:50,  1.66it/s]

Running loglikelihood requests:  16%|█▋        | 73/448 [00:48<03:41,  1.69it/s]

Running loglikelihood requests:  18%|█▊        | 81/448 [00:53<03:31,  1.73it/s]

Running loglikelihood requests:  20%|█▉        | 89/448 [00:57<03:23,  1.76it/s]

Running loglikelihood requests:  22%|██▏       | 97/448 [01:01<03:16,  1.79it/s]

Running loglikelihood requests:  23%|██▎       | 105/448 [01:06<03:09,  1.81it/s]

Running loglikelihood requests:  25%|██▌       | 113/448 [01:10<03:03,  1.82it/s]

Running loglikelihood requests:  27%|██▋       | 121/448 [01:14<02:57,  1.84it/s]

Running loglikelihood requests:  29%|██▉       | 129/448 [01:19<02:52,  1.85it/s]

Running loglikelihood requests:  31%|███       | 137/448 [01:23<02:47,  1.85it/s]

Running loglikelihood requests:  32%|███▏      | 145/448 [01:27<02:43,  1.86it/s]

Running loglikelihood requests:  34%|███▍      | 153/448 [01:32<02:38,  1.86it/s]

Running loglikelihood requests:  36%|███▌      | 161/448 [01:36<02:35,  1.85it/s]

Running loglikelihood requests:  38%|███▊      | 169/448 [01:40<02:30,  1.86it/s]

Running loglikelihood requests:  40%|███▉      | 177/448 [01:44<02:26,  1.85it/s]

Running loglikelihood requests:  41%|████▏     | 185/448 [01:49<02:22,  1.85it/s]

Running loglikelihood requests:  43%|████▎     | 193/448 [01:53<02:18,  1.84it/s]

Running loglikelihood requests:  45%|████▍     | 201/448 [01:58<02:13,  1.85it/s]

Running loglikelihood requests:  47%|████▋     | 209/448 [02:02<02:09,  1.85it/s]

Running loglikelihood requests:  48%|████▊     | 217/448 [02:06<02:04,  1.86it/s]

Running loglikelihood requests:  50%|█████     | 225/448 [02:10<01:59,  1.86it/s]

Running loglikelihood requests:  52%|█████▏    | 233/448 [02:15<01:54,  1.87it/s]

Running loglikelihood requests:  54%|█████▍    | 241/448 [02:19<01:50,  1.88it/s]

Running loglikelihood requests:  56%|█████▌    | 249/448 [02:23<01:45,  1.88it/s]

Running loglikelihood requests:  57%|█████▋    | 257/448 [02:27<01:41,  1.89it/s]

Running loglikelihood requests:  59%|█████▉    | 265/448 [02:31<01:36,  1.90it/s]

Running loglikelihood requests:  61%|██████    | 273/448 [02:36<01:31,  1.90it/s]

Running loglikelihood requests:  63%|██████▎   | 281/448 [02:40<01:27,  1.91it/s]

Running loglikelihood requests:  65%|██████▍   | 289/448 [02:44<01:22,  1.93it/s]

Running loglikelihood requests:  66%|██████▋   | 297/448 [02:48<01:17,  1.94it/s]

Running loglikelihood requests:  68%|██████▊   | 305/448 [02:52<01:13,  1.94it/s]

Running loglikelihood requests:  70%|██████▉   | 313/448 [02:56<01:09,  1.95it/s]

Running loglikelihood requests:  72%|███████▏  | 321/448 [03:00<01:05,  1.94it/s]

Running loglikelihood requests:  73%|███████▎  | 329/448 [03:04<01:01,  1.95it/s]

Running loglikelihood requests:  75%|███████▌  | 337/448 [03:08<00:57,  1.95it/s]

Running loglikelihood requests:  77%|███████▋  | 345/448 [03:13<00:52,  1.94it/s]

Running loglikelihood requests:  79%|███████▉  | 353/448 [03:17<00:48,  1.94it/s]

Running loglikelihood requests:  81%|████████  | 361/448 [03:21<00:44,  1.95it/s]

Running loglikelihood requests:  82%|████████▏ | 369/448 [03:25<00:40,  1.95it/s]

Running loglikelihood requests:  84%|████████▍ | 377/448 [03:29<00:36,  1.96it/s]

Running loglikelihood requests:  86%|████████▌ | 385/448 [03:33<00:32,  1.97it/s]

Running loglikelihood requests:  88%|████████▊ | 393/448 [03:37<00:27,  1.98it/s]

Running loglikelihood requests:  90%|████████▉ | 401/448 [03:41<00:23,  1.99it/s]

Running loglikelihood requests:  91%|█████████▏| 409/448 [03:45<00:19,  2.00it/s]

Running loglikelihood requests:  93%|█████████▎| 417/448 [03:49<00:15,  2.00it/s]

Running loglikelihood requests:  95%|█████████▍| 425/448 [03:53<00:11,  2.01it/s]

Running loglikelihood requests:  97%|█████████▋| 433/448 [03:57<00:07,  2.01it/s]

Running loglikelihood requests:  98%|█████████▊| 441/448 [04:01<00:03,  2.01it/s]

Running loglikelihood requests: 100%|██████████| 448/448 [04:01<00:00,  1.86it/s]

                 mmlu_flan_n_shot_loglikelihood_machine_learning
name             mmlu_flan_n_shot_loglikelihood_machine_learning
alias            mmlu_flan_n_shot_loglikelihood_machine_learning
sample_len                                                   112
acc,none                                                0.491071
acc_stderr,none                                          0.04745

In [ ]:
results_instruct_mmlu_0shot = eval_mmlu(model_instruct, num_fewshot=0)
pd.DataFrame(results_instruct_mmlu_0shot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:Overwriting default num_fewshot of mmlu_flan_n_shot_loglikelihood_machine_learning from None to 0

  0%|          | 0/112 [00:00<?, ?it/s]

 54%|█████▎    | 60/112 [00:00<00:00, 598.64it/s]

100%|██████████| 112/112 [00:00<00:00, 603.19it/s]

Tokenizing inputs:   0%|          | 0/448 [00:00<?, ?it/s]

Tokenizing inputs:  43%|████▎     | 194/448 [00:00<00:00, 1938.10it/s]

Tokenizing inputs:  87%|████████▋ | 390/448 [00:00<00:00, 1948.82it/s]

Tokenizing inputs: 100%|██████████| 448/448 [00:00<00:00, 1813.69it/s]

Running loglikelihood requests:   0%|          | 0/448 [00:00<?, ?it/s]

Running loglikelihood requests:   0%|          | 1/448 [00:01<11:09,  1.50s/it]

Running loglikelihood requests:   2%|▏         | 9/448 [00:02<01:52,  3.91it/s]

Running loglikelihood requests:   4%|▍         | 17/448 [00:03<01:16,  5.66it/s]

Running loglikelihood requests:   6%|▌         | 25/448 [00:04<01:02,  6.75it/s]

Running loglikelihood requests:   7%|▋         | 33/448 [00:05<00:53,  7.82it/s]

Running loglikelihood requests:   9%|▉         | 41/448 [00:06<00:46,  8.66it/s]

Running loglikelihood requests:  11%|█         | 49/448 [00:06<00:40,  9.79it/s]

Running loglikelihood requests:  13%|█▎        | 57/448 [00:07<00:36, 10.71it/s]

Running loglikelihood requests:  15%|█▍        | 65/448 [00:07<00:33, 11.41it/s]

Running loglikelihood requests:  16%|█▋        | 73/448 [00:08<00:31, 11.95it/s]

Running loglikelihood requests:  18%|█▊        | 81/448 [00:09<00:29, 12.44it/s]

Running loglikelihood requests:  20%|█▉        | 89/448 [00:09<00:28, 12.81it/s]

Running loglikelihood requests:  22%|██▏       | 97/448 [00:10<00:26, 13.10it/s]

Running loglikelihood requests:  23%|██▎       | 105/448 [00:10<00:25, 13.34it/s]

Running loglikelihood requests:  25%|██▌       | 113/448 [00:11<00:24, 13.48it/s]

Running loglikelihood requests:  27%|██▋       | 121/448 [00:11<00:23, 13.65it/s]

Running loglikelihood requests:  29%|██▉       | 129/448 [00:12<00:23, 13.76it/s]

Running loglikelihood requests:  31%|███       | 137/448 [00:13<00:22, 13.85it/s]

Running loglikelihood requests:  32%|███▏      | 145/448 [00:13<00:21, 14.00it/s]

Running loglikelihood requests:  34%|███▍      | 153/448 [00:14<00:21, 14.03it/s]

Running loglikelihood requests:  36%|███▌      | 161/448 [00:14<00:20, 14.08it/s]

Running loglikelihood requests:  38%|███▊      | 169/448 [00:15<00:19, 14.40it/s]

Running loglikelihood requests:  40%|███▉      | 177/448 [00:15<00:18, 14.63it/s]

Running loglikelihood requests:  41%|████▏     | 185/448 [00:16<00:17, 14.79it/s]

Running loglikelihood requests:  43%|████▎     | 193/448 [00:16<00:17, 14.93it/s]

Running loglikelihood requests:  45%|████▍     | 201/448 [00:17<00:16, 15.10it/s]

Running loglikelihood requests:  47%|████▋     | 209/448 [00:17<00:15, 15.22it/s]

Running loglikelihood requests:  48%|████▊     | 217/448 [00:18<00:15, 15.31it/s]

Running loglikelihood requests:  50%|█████     | 225/448 [00:18<00:14, 15.41it/s]

Running loglikelihood requests:  52%|█████▏    | 233/448 [00:19<00:13, 15.50it/s]

Running loglikelihood requests:  54%|█████▍    | 241/448 [00:19<00:13, 15.56it/s]

Running loglikelihood requests:  56%|█████▌    | 249/448 [00:20<00:12, 15.63it/s]

Running loglikelihood requests:  57%|█████▋    | 257/448 [00:20<00:12, 15.67it/s]

Running loglikelihood requests:  59%|█████▉    | 265/448 [00:21<00:11, 15.75it/s]

Running loglikelihood requests:  61%|██████    | 273/448 [00:21<00:11, 15.82it/s]

Running loglikelihood requests:  63%|██████▎   | 281/448 [00:22<00:10, 15.82it/s]

Running loglikelihood requests:  65%|██████▍   | 289/448 [00:22<00:09, 16.36it/s]

Running loglikelihood requests:  66%|██████▋   | 297/448 [00:23<00:09, 16.77it/s]

Running loglikelihood requests:  68%|██████▊   | 305/448 [00:23<00:08, 17.07it/s]

Running loglikelihood requests:  70%|██████▉   | 313/448 [00:24<00:07, 17.23it/s]

Running loglikelihood requests:  72%|███████▏  | 321/448 [00:24<00:07, 17.42it/s]

Running loglikelihood requests:  73%|███████▎  | 329/448 [00:25<00:06, 17.63it/s]

Running loglikelihood requests:  75%|███████▌  | 337/448 [00:25<00:06, 17.79it/s]

Running loglikelihood requests:  77%|███████▋  | 345/448 [00:26<00:05, 17.95it/s]

Running loglikelihood requests:  79%|███████▉  | 353/448 [00:26<00:05, 18.10it/s]

Running loglikelihood requests:  81%|████████  | 361/448 [00:26<00:04, 18.32it/s]

Running loglikelihood requests:  82%|████████▏ | 369/448 [00:27<00:04, 18.65it/s]

Running loglikelihood requests:  84%|████████▍ | 377/448 [00:27<00:03, 18.93it/s]

Running loglikelihood requests:  86%|████████▌ | 385/448 [00:28<00:03, 19.97it/s]

Running loglikelihood requests:  88%|████████▊ | 393/448 [00:28<00:02, 20.82it/s]

Running loglikelihood requests:  90%|████████▉ | 401/448 [00:28<00:02, 21.38it/s]

Running loglikelihood requests:  91%|█████████▏| 409/448 [00:29<00:01, 21.88it/s]

Running loglikelihood requests:  93%|█████████▎| 417/448 [00:29<00:01, 22.48it/s]

Running loglikelihood requests:  95%|█████████▍| 425/448 [00:29<00:00, 23.20it/s]

Running loglikelihood requests:  97%|█████████▋| 433/448 [00:30<00:00, 23.71it/s]

Running loglikelihood requests:  98%|█████████▊| 441/448 [00:30<00:00, 24.31it/s]

Running loglikelihood requests: 100%|██████████| 448/448 [00:30<00:00, 14.76it/s]

                 mmlu_flan_n_shot_loglikelihood_machine_learning
name             mmlu_flan_n_shot_loglikelihood_machine_learning
alias            mmlu_flan_n_shot_loglikelihood_machine_learning
sample_len                                                   112
acc,none                                                0.526786
acc_stderr,none                                          0.04739

In [ ]:
results_instruct_mmlu_cot = eval_mmlu_cot(model_instruct)
pd.DataFrame(results_instruct_mmlu_cot["results"])

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.

WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration

WARNING:lm_eval.evaluator:generation_kwargs: {'max_gen_toks': 384} specified through cli, these settings will update set parameters in yaml tasks. Ensure 'do_sample=True' for non-greedy decoding!

  0%|          | 0/11 [00:00<?, ?it/s]

100%|██████████| 11/11 [00:00<00:00, 409.39it/s]

Running generate_until requests:   0%|          | 0/11 [00:00<?, ?it/s]

Running generate_until requests:   9%|▉         | 1/11 [00:32<05:25, 32.50s/it]

Running generate_until requests:  45%|████▌     | 5/11 [01:04<01:10, 11.72s/it]

Running generate_until requests:  82%|████████▏ | 9/11 [01:37<00:19,  9.72s/it]

Running generate_until requests: 100%|██████████| 11/11 [01:37<00:00,  8.83s/it]

                                     mmlu_flan_cot_zeroshot_machine_learning
name                                 mmlu_flan_cot_zeroshot_machine_learning
alias                                mmlu_flan_cot_zeroshot_machine_learning
sample_len                                                                11
exact_match,strict-match                                            0.181818
exact_match_stderr,strict-match                                     0.121967
exact_match,flexible-extract                                        0.363636
exact_match_stderr,flexible-extract                                  0.15212

---

# Cierre · Comparativa base vs instruct

La pregunta del modulo: **¿cuanto sube por instruct tuning?** (spoiler: depende de COMO lo midas).

Construimos una tabla que junta los benchmarks de ambos modelos (MMLU-ML en 5-shot, 0-shot y CoT) + el delta.

> Nota tecnica sobre HellaSwag · usamos `acc_norm` (length-normalized accuracy), no `acc`. La razon: HellaSwag es multiple-choice con opciones de longitud variable, y un modelo tiende a preferir respuestas mas cortas si no normalizas por longitud. **`acc_norm` es la metrica canonica** que se reporta en el Open LLM Leaderboard.

In [ ]:
def safe_extract(results, task, metric):
    """Extrae metrica, devuelve None si no existe."""
    try:
        return results["results"][task].get(metric)
    except (KeyError, TypeError):
        return None

filas = [
    {
        "Benchmark": "HellaSwag (acc_norm)",
        "base": safe_extract(results_base_basic, "hellaswag", "acc_norm,none"),
        "instruct": safe_extract(results_instruct_basic, "hellaswag", "acc_norm,none"),
    },
    {
        "Benchmark": "ARC-Easy (acc)",
        "base": safe_extract(results_base_basic, "arc_easy", "acc,none"),
        "instruct": safe_extract(results_instruct_basic, "arc_easy", "acc,none"),
    },
    {
        "Benchmark": "MMLU-ML 5-shot (acc)",
        "base": safe_extract(results_base_mmlu_5shot, TASK_MMLU, "acc,none"),
        "instruct": safe_extract(results_instruct_mmlu_5shot, TASK_MMLU, "acc,none"),
    },
    {
        "Benchmark": "MMLU-ML 0-shot (acc)",
        "base": safe_extract(results_base_mmlu_0shot, TASK_MMLU, "acc,none"),
        "instruct": safe_extract(results_instruct_mmlu_0shot, TASK_MMLU, "acc,none"),
    },
    {
        "Benchmark": "MMLU-ML CoT (exact_match)",
        "base": safe_extract(results_base_mmlu_cot, TASK_MMLU_COT, "exact_match,flexible-extract"),
        "instruct": safe_extract(results_instruct_mmlu_cot, TASK_MMLU_COT, "exact_match,flexible-extract"),
    },
]

df = pd.DataFrame(filas)
df["delta_pp"] = (df["instruct"] - df["base"]).round(3)
df["delta_%"] = ((df["instruct"] - df["base"]) / df["base"] * 100).round(1)

df

                   Benchmark      base  instruct  delta_pp  delta_%
0       HellaSwag (acc_norm)  0.620000  0.570000    -0.050     -8.1
1             ARC-Easy (acc)  0.746000  0.786000     0.040      5.4
2       MMLU-ML 5-shot (acc)  0.651786  0.491071    -0.161    -24.7
3       MMLU-ML 0-shot (acc)  0.535714  0.526786    -0.009     -1.7
4  MMLU-ML CoT (exact_match)  0.818182  0.363636    -0.455    -55.6

## Interpretacion · que dicen los numeros

Ejecucion de referencia (oct-2026 · T4 · 4-bit NF4 con compute fp16 · `LIMIT = 500`). Tus numeros pueden moverse unas centesimas:

| Benchmark | base | instruct | Lectura |
|---|---|---|---|
| HellaSwag (acc_norm, n=500) | 0.62 | 0.57 | Baja ligeramente · el post-entrenamiento no anade conocimiento y desplaza al modelo de la "continuacion de texto" |
| ARC-Easy (acc, n=500) | 0.75 | 0.79 | Sube un poco (stderr ~0.02) |
| MMLU-ML 5-shot (n=112) | 0.65 | 0.49 | **Baja** · el instruct evaluado sin su chat template pierde calibracion en el formato "(A)/(B)/..." |
| MMLU-ML 0-shot (n=112) | 0.54 | 0.53 | Igual (stderr ~0.05) |
| MMLU-ML CoT (flexible, n=11) | 0.82 | 0.36 | El base razona muy bien; el instruct cae. Con 11 preguntas, es una señal, no una prueba |

**La hipotesis clasica NO se cumple aqui, y esa es la leccion:**

1. **Los base de 2025-2026 ya no son "tontos".** `Qwen3-4B-Base` se pre-entrena con mucho texto de razonamiento e instrucciones: sabe hacer CoT y responder A/B/C/D sin post-entrenamiento.
2. **El protocolo manda.** Medimos el instruct con prompts crudos y sin chat template, que no es como se usa. Un modelo post-entrenado (y con modo thinking) fuera de su formato suele puntuar peor: es una de las razones por las que el mismo modelo saca cifras distintas en distintos leaderboards. En lm-eval puedes repetirlo con `apply_chat_template=True` en `simple_evaluate`.
3. **Muestras pequenas = ruido.** CoT con 11 preguntas tiene un stderr de ~0.13; antes de concluir, mira el error estandar.

**Conclusion practica** · no elijas modelo por un numero suelto de benchmark: compara siempre con el MISMO protocolo, el adecuado para cada modelo (chat template para los instruct), y con muestras suficientes. Y para tu caso de uso, la eval que manda es la tuya (módulo de evaluación de LLM apps, clase 6).

## Comparativa con frontier 2026

Tus numeros en MMLU machine_learning vs la frontera de octubre 2026 (slide 20):

- Frontier por API (Gemini 3 Pro, Claude Opus 4.5) · MMLU-Pro ~0.90 (techo actual)
- Gemma 4 E4B (local, cabe en T4) · MMLU-Pro 0.694 (model card oficial de Google)
- Qwen3-4B (este notebook) · tu MMLU-ML de arriba (ojo: MMLU clasico, no MMLU-Pro; no son directamente comparables)

El gap con el frontier es **real** para un modelo de 4B (~20 puntos de MMLU-Pro). Pero acordate de las slides 20 y 26 · **MMLU clasico esta saturado**. Para diferenciar frontier hoy se mira MMLU-Pro, GPQA Diamond, SWE-bench Pro o HLE.

## Siguiente paso · evalua tu modelo fine-tuneado

Repite este notebook con tus adapters de Fine-tuning: el del lab 04 (Milei, QLoRA sobre Qwen3.5) o el del lab 05 (distillation, Gemma 4 E2B). `HFLM` acepta el modelo con el adapter cargado (`PeftModel.from_pretrained(base, "tu_usuario/milei-qlora-adapter")`), igual que en el lab 09 de Fine-tuning. Lectura: estos benchmarks generales miden **retencion**. Un fine-tune de estilo o de dominio no deberia subir HellaSwag; lo que buscas es que **no baje**. Lo que tu fine-tune gana (estilo, tu tarea) se mide con una eval propia, como hiciste en el lab 09 de Fine-tuning.

Eso es **el cierre real del flow Fine-tuning → Evaluación**.

## Lighteval · la alternativa moderna (mencion)

`lighteval` de HuggingFace cubre el mismo proposito que `lm-evaluation-harness` con API mas integrada al ecosistema HF. Sintaxis tipica:

```bash
pip install lighteval[accelerate]
lighteval accelerate \
    --model_args "pretrained=Qwen/Qwen3-4B,load_in_4bit=True" \
    --tasks "leaderboard|hellaswag|0|0,leaderboard|arc:easy|0|0" \
    --output_dir ./results
```

Misma idea, distinto wrapper. Si trabajas en HuggingFace stack, lighteval encaja mejor.